### ISSUE TITLE
Branch is created, but PR is not

### ISSUE THREAD

**Issue by ohjames** [greenkeeperio/greenkeeper#1065]
This issue was closed in 2017: https://github.com/greenkeeperio/greenkeeper/issues/342

As per my comment at the bottom, it is still an issue.

Greekeeper created 5 branches: https://circleci.com/gh/ohjames/rxjs-websockets

Not a single PR though (beyond the initial PR to enable greekeeper): https://github.com/ohjames/rxjs-websockets/pulls?utf8=%E2%9C%93&q=is%3Apr

**Comment by devilesk** [comment]
I just stumbled upon this behavior myself and went looking for answers, but based on what I found out I don't think this is really an issue. It's just confusion about how Greenkeeper works and why PRs aren't actually warranted in these cases.

Basically, Greenkeeper doesn't open PRs for in-range dependency updates with passing tests as described in [their docs](https://greenkeeper.io/docs.html#what-greenkeeper-does).

For example, you had `"sinon": "^7.2.2"` in your package.json and [Greenkeeper tested 7.3.0](https://circleci.com/gh/ohjames/rxjs-websockets/109). The test passed, which means the update wouldn't break your build. And since `7.3.0` falls in the range specified by `^7.2.2` there's no change that requires a PR. That's because anyone who tried to `npm install` would get the highest version satisfying the `^7.2.2` range which would have been `7.3.0` at the time and Greenkeeper just confirmed the build passes with that version.

You would see a PR if an out of range update happened like if sinon released a `8.0.0` version, because that implies breaking changes from 7.x.x versions according to SemVer. You would also see a PR if `7.3.0` didn't pass your tests. That would be an issue requiring a PR, because that's the version people would get when installing according to `^7.2.2` and not passing tests means it's a breaking change.

If you wanted PRs for every single minor version bump then you need to define stricter ranges. So instead of `^7.2.2` specify `~7.2.2` which would make `7.3.0` out of range. Or you can pin to the exact version by not using a caret or tilde and just specifying `7.2.2`. In your project when you switched to using Renovate it did that and [pinned all your dependencies for you](https://github.com/ohjames/rxjs-websockets/commit/fbe9c50a4c33d559fbd2d5e3a50ca6ffe7309cb3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

**Comment by ohjames** [comment]
@devilsek in that case, why did greenkeeper create the branch and trigger CI? You'd expect it to either create the branch and open the PR, or do neither, but not one or the other.

**Comment by devilesk** [comment]
A new branch is created so that it can bump your dependency to the new version and trigger CI to run tests to make sure your project still builds with that new version. If the tests pass there's no need for a PR because no changes need to be made.

**Comment by ohjames** [comment]
Cool thanks for the info!
