### ISSUE TITLE
Does Greenkeeper stop submitting PR for a particular dependency after I close a previous PR for that dependency?

### ISSUE THREAD

**Issue by nartc** [greenkeeperio/greenkeeper#1135]
As question stated. I have two libraries, one (A) depends on the other (B). I released a major version of (B) the other day and Greenkeeper opens a PR for that on (A). However, there were some merge conflicts at the time on (A) so I closed the PR without merging it. 

Since then, I've released two minor versions of (B) already and Greenkeeper doesn't seem to pick it up anymore.

**Comment by travi** [comment]
are you depending on a specific version or a semver range? do [these details](https://greenkeeper.io/docs.html#greenkeeper-step-by-step) help answer your question?

**Comment by nartc** [comment]
It’s semver range. And I closed the PR when greenkeeper tried to update the dependency to an out-of-range (from ^1.1.8 to 2.0.0). 

Then I manually up the dependency version, migrate the changes then release a new version. After that, the dependency has released two minor version (2.0.1 and 2.0.2) but greenkeeper doesn’t seem to pick it up. 

I have the dependency listed as: ^2.0.0 right now.

**Comment by travi** [comment]
> I have the dependency listed as: ^2.0.0 right now.

if that is true, versions `2.0.1` and `2.0.2` are within the range you specified and greenkeeper will not send a PR. it will still open a branch and run your checks. if your checks fail, it will open an issue to inform you of that. otherwise, it is working as expected to do nothing.

if you want the version to be updated more often, you need to adjust the range that you specify to be more narrow.

**Comment by nartc** [comment]
Thanks for clarifying that.
