### ISSUE TITLE
if you guys made a PR w/ bluebird@3.1.4 w/ passing tests, don't make another one for bluebird@3.1.2

### ISSUE THREAD

**Issue by jonathanong** [greenkeeperio/greenkeeper#117]
i think this is because you guys were delayed and ran updates latest -> oldest, so you guys ran 3.1.4 before you ran 3.1.2

**Comment by boennemann** [comment]
Hey @jonathanong,

sorry for the issues. These PR's shouldn't have appeared out of order in the first place – this was caused by a short hiccup in our worker queue.

We will soon land a feature so that Greenkeeper cleans up after itself: https://github.com/greenkeeperio/greenkeeper/issues/62

Thanks for using Greenkeeper.

Best,
Stephan

**Comment by boennemann** [comment]
We started to roll out our auto-closing feature. Details: https://github.com/greenkeeperio/greenkeeper/issues/62#issuecomment-176248343
