### ISSUE TITLE
Can't enable support for repository in an organization

### ISSUE THREAD

**Issue by Widdershin** [greenkeeperio/greenkeeper#14]
I want to set up greenkeeper for [cyclejs/cycle-time-travel](/cyclejs/cycle-time-travel).

After successfully running `greenkeeper login`, when I attempt to run `greenkeeper enable` I see this:
 ```
🌴  info enable The GitHub slug is: cyclejs/cycle-time-travel
🌴  ERR! enable A repo with this slug doesn’t exist on GitHub
```
As you can see from the link above, the repository does in fact exist at that slug.

Having a look at the code, that message is displayed when the response has a status code of 400. 

It might be because I'm not the owner of the organization, but I think the owner has already granted greenkeeper access to the organization.

I also ran into the same problem on an organization that I am the owner of.

Any thoughts?

**Comment by boennemann** [comment]
Hey @Widdershin,

thanks for reporting this issue. This seems to be a problem for a few people, but we haven't yet nailed down the exact reason why it's happening.

For one the error message isn't really good, because there are more reasons for the 400 than the repo not existing, but it seems like we can't access the repo during sync.

There is already an issue on our support repo, so I'm closing this one. Please track the progress there.

https://github.com/greenkeeperio/support/issues/4

Thanks again :)
Stephan
