### ISSUE TITLE
Reported broken build even after build succeeded

### ISSUE THREAD

**Issue by ranisalt** [greenkeeperio/greenkeeper#140]
Greenkeeper has opened a pull request in my repo ([here](https://github.com/ranisalt/node-argon2/pull/23)) reporting there was  a failure to build, but as you can see every check has passed, even code coverage.

**Comment by boennemann** [comment]
Hey @ranisalt,

thanks for your bug report. Sometimes builds fail because of some random factors that go away after restarting the build. Can you rule out that someone restarted the build after the PR was created?

If that wasn't the case we'll investigate what was happening, especially what data GitHub sent us, to rule out this bug and to prevent any false alarms in the future.
If this keeps happening again please let us know here, so we can identify the problem.


Thanks for using Greenkeeper,
Stephan

**Comment by ranisalt** [comment]
That might be the case, yes. But if there is an error with Travis and not with the code itself, I think greenkeeper should warn differently, not asserting that "**This means your software is now malfunctioning, because of this update.**", is it possible?

Thanks for the answer :D

**Comment by boennemann** [comment]
Thanks for your quick reply. 99% of the time flaky tests aren't really a problem with the CI server, but with the test setup. It's also something we can't really detect – the decision whether something was "just a flaky build" has to be made by a human.

However I agree that the message is too definite, so we'll weaken it a bit.

Thanks for your report.

Best,
Stephan
