### ISSUE TITLE
Show what parts of changelogs have been tested in previous builds

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#147]
When I look at this example https://github.com/hoodiehq/hoodie-client-store/pull/87, I wonder if it would be possible for the greenkeeper bot to something like "tested with build on March 1st, 2016, 11:12am UTC" above the line "`3227068` v4.5.0 "

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations.

With the new Greenkeeper this issue is resolved and you can try it out today: https://github.com/integration/greenkeeper
Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
