### ISSUE TITLE
Allow customization of commit messages & pull requests

### ISSUE THREAD

**Issue by tusbar** [greenkeeperio/greenkeeper#153]
Hi,

It would be nice to have a way to customize a few things:
- [ ] commit messages / pull requests names (through templating maybe)
- [x] pull requests labels (I use a `dependency` label for all that stuff)

**Comment by finnp** [comment]
Hey @tusbar,

your second request is actually already possible. Just add this to the `package.json` of your project and we will use your `dependency` label instead of `greenkeeper`:
```json
"greenkeeper": {
   "label": "dependency"
}
```

We are probably also going to add support for commit message / pull request name customisation.

**Comment by danielnbarbosa** [comment]
any thoughts on whether this feature will be added?  would be very helpful for us as we need to track all changes through pivotal tracker and customizing the commit message would allow us to automate this process instead of manually updating the merge message.

**Comment by finnp** [comment]
@danielnbarbosa Hey, it might still need some time, but I'm fairly sure we will be adding this feature. ☺️

**Comment by danielnbarbosa** [comment]
thanks @finnp.  looking forward to it!

**Comment by Arcanemagus** [comment]
I was looking into this and here's what I found. I'm sure I've probably missed a location where commit messages are created, but I wanted to get the conversation started here.

From what I found there are five locations where commit messages are created.

This is where a "pin" commit is created when a build has failed and GK is attempting to pin a previous version.
https://github.com/greenkeeperio/greenkeeper/blob/e3b2ec236139c0202df840f33187d75deca9222e/lib/open-issue.js#L75

Here is where the normal upgrade commits are created.
https://github.com/greenkeeperio/greenkeeper/blob/e3b2ec236139c0202df840f33187d75deca9222e/jobs/create-version-branch.js#L140-L151

As well as 3 potential commits within the initial branch creation:
https://github.com/greenkeeperio/greenkeeper/blob/e3b2ec236139c0202df840f33187d75deca9222e/jobs/create-initial-branch.js#L156
https://github.com/greenkeeperio/greenkeeper/blob/e3b2ec236139c0202df840f33187d75deca9222e/jobs/create-initial-branch.js#L171
https://github.com/greenkeeperio/greenkeeper/blob/e3b2ec236139c0202df840f33187d75deca9222e/jobs/create-initial-branch.js#L177
----

In order to support commit message formats other than Angular, I'm currently thinking of something along these lines in `package.json`:
```json
{
  "greenkeeper": {
    "commitMessages": {
      "initialBadge": "docs(readme): add Greenkeeper badge",
      "initialDependencies": "chore(package): update dependencies",
      "initialBranches": "chore(travis): whitelist greenkeeper branches",
      "dependencyUpdate": "chore(package): update ${dependency} to version ${version}",
      "devDependencyUpdate": "fix(package): update ${dependency} to version ${version}",
      "dependencyPin" : "chore: pin ${dependency} to ${oldVersionResolved}",
      "devDependencyPin": "fix: pin ${dependency} to ${oldVersionResolved}",
      "closes": "\n\nCloses #${number}"
  }
}
```

There are a couple of different ways this could be done, since the last 5 require some form of templating already it _might_ be possible to combine the two dependency types together, but that might limit some commit message styles. The templating style also of course can be changed, right now it is a direct clone of the JS strings.

Am I missing some strings?
Is there a better way to accomplish this?
