### ISSUE TITLE
Commit messages in PR cause incorrect issue linking

### ISSUE THREAD

**Issue by SpainTrain** [greenkeeperio/greenkeeper#159]
When GK opens a PR, in the PR description it places the commit message for every new commit in the target dependency's repo.  Many of these commit messages have `fixes #<X>`, `closes #<Y>`, etc. This has the unintended consequence of linking to issues *within* the repo being watch, even though the issue being referenced is in the target dependency's repo.  If the GK PR is merged without removing these directives, then completely unrelated issues may be closed as a result.

**Comment by janl** [comment]
Heya, thanks for the report. Can you point to a sample PR where this happens?

**Comment by finnp** [comment]
Great report. I didn't even know that closing issues from PRs bodies was a thing.

Here are two helpful articles by GitHub about this:
https://github.com/blog/1506-closing-issues-via-pull-requests
https://help.github.com/articles/closing-issues-via-commit-messages/

I guess at least for those keywords a #xx should always be transformed into slug/#xx.

However since "Closes slug/#xx" is also a valid syntax, there could be rare scenarios where this is unwanted.
For example: Within one org a PR is merged in one repository, which closes an issue, this issue however is later reopened. Now a greenkeeper PR on another repo of this org could close the issue again when merged.

**Comment by SpainTrain** [comment]
> Can you point to a sample PR where this happens?

It has been happening in a private repo, so I will need to contrive a reproduction in a public repo when I get a chance (or I will link to a public PR if I happen upon one exhibiting this issue).

**Comment by boennemann** [comment]
We had this happening before, at least in the release notes, and so we started using the GitHub API to render the Markdown in the context of the source repository first. https://developer.github.com/v3/markdown/#parameters

I'm a bit surprised to see that apparently we oversaw the same thing happening with commits messages. We need to take these extra steps there, too.

Thanks for the report, we'll try to get a solution ready as fast as possible.

**Comment by SpainTrain** [comment]
Thanks @boennemann!  To confirm: I can cancel my plan to create a repro case?

**Comment by SpainTrain** [comment]
There seems to be a regression on this.  Here is an example PR description body that is causing the issue link issue - https://gist.github.com/SpainTrain/60c8fe9d721d91ed959694dd28fb71b9

**Comment by SpainTrain** [comment]
@boennemann could we reopen this?  This is affecting us daily.  Thanks!

(gk username "HomeZenBot")

**Comment by SpainTrain** [comment]
related: https://github.com/greenkeeperio/greenkeeper/issues/305
