### ISSUE TITLE
Rebasing appears to lose non-greenkeeper commits

### ISSUE THREAD

**Issue by orangejulius** [greenkeeperio/greenkeeper#173]
Hello greenkeeper team,
Your recent change to automatically rebase GK pull requests when a prior GK PR is merged is great for nice clean git histories, so thank you for that.

However it seems like it's not really doing a rebase, and instead is re-creating the commit and force-pushing, which has the side effect of wiping out any other commits in the branch. Since the PR body itself says to "use this branch to work on adaptions and fixes", this has the potential to lose some very important work.

Hopefully you can fix it soon. Cheers!

**Comment by boennemann** [comment]
Hey @orangejulius,

thanks for this report. As a quick fix, to not lose data, we're now leaving branches with additional commits alone. We might work on _actually_ rebasing those as well in the future.

This change is effective since April 25th, but I failed to communicate it. Sorry for that.

Thanks,
Stephan
