### ISSUE TITLE
Use GPG key to sign commits

### ISSUE THREAD

**Issue by OmgImAlexis** [greenkeeperio/greenkeeper#183]
Since github now shows if someone's signed a commit with their GPG key I'd be nice to have greenkeeper sign all the commits it creates as well.

**Comment by JuanitoFatas** [comment]
@OmgImAlexis [This section in Verify Page](https://greenkeeper.io/verify.html#gpg) and this answer probably can clarify: http://stackoverflow.com/a/10166916/517868.

**Comment by OmgImAlexis** [comment]
What happens for repos that have rules about only allowing GPG signed commits? A few repos I'm a major member of are moving to only allowing commits that've been signed and still want to use greenkeeper.

**Comment by janl** [comment]
@OmgImAlexis for the foreseeable future, these projects won’t be able to use Greenkeeper then, sorry :/

As laid out in https://github.com/greenkeeperio/greenkeeper/issues/92#issuecomment-212317355, we are a small shop, and adding GPG to our commits is a significant feature (there are a number of complexities that might not be immediately obvious) that we can’t easily justify adding (especially if the reason is a questionable policy to begin with ;).

Out of curiosity, which organisations you are part of have this policy in place today?

**Comment by OmgImAlexis** [comment]
We're having talks internally about requiring GPG signed commits on github.com/pymedusa/SickRage and github.com/Sickrage/SickRage.

**Comment by janl** [comment]
@OmgImAlexis thanks! Those look like Python projects. Greenkeeper only works with packages that use a `package.json` file in the `npm` sense. We technically don’t care about the implementation language, but we do rely on npm semantics, which usually means JavaScript projects only.

**Comment by OmgImAlexis** [comment]
Since we use npm to run out builds for the front end both projects should be fine working with greenkeeper, no?

**Comment by janl** [comment]
@OmgImAlexis I only skimmed the repos, but I couldn’t find a `package.json`. Greenkeeper only works with packages that have a top-level `package.json` file to specify dependencies and its own version.

**Comment by paularmstrong** [comment]
Can this discussion be reopened?

> adding GPG to our commits is a significant feature (there are a number of complexities that might not be immediately obvious) that we can’t easily justify adding (especially if the reason is a questionable policy to begin with ;).

Specifically, what are the complexities? Have things changed in the past 3 years that would make this less difficult?

I think this is less of a policy issue and more of a security/safety request on behalf of greenkeeper.
