### ISSUE TITLE
feature: enable only for dependencies

### ISSUE THREAD

**Issue by iamstarkov** [greenkeeperio/greenkeeper#193]
First of all, thank you for this awesome software

So right now i enabled greenkeeper for tens of my repos and it sends me updates for all my deps. At the same time i use nearly the same set of devDeps for every project. Once my test-runner or transpiler got update im instantly getting a lot of pull-requests. Its useful, but annoying as well.

I would be much more happier if i will be able to enable greenkeeper only for production dependencies (so devDeps will not get bump from greenkeeper). is there any way to do it now?

**Comment by janl** [comment]
Heya, thank you for your kind words about Greenkeeper! 🌴

Your best bet *right now* would be the (undocumented) `ignore` feature in your `package.json` file(s):

```json
…
  "greenkeeper": {
    "ignore": ["dep1", "dep2", "devDep1", "…"]
  }
…
```

This is undocumented on purpose, because we don’t guarantee this staying around forever in this form, but once we decide on a final syntax for this, we will auto-migrate your projects, so no worries about adopting this now.

Feel free to re-open if you have any further questions on this topic.
