### ISSUE TITLE
Support for npm hooks

### ISSUE THREAD

**Issue by leo** [greenkeeperio/greenkeeper#199]
npm now provides [a feature](http://blog.npmjs.org/post/145260155635/introducing-hooks-get-notifications-of-npm?utm_source=tumblr&utm_medium=blog&utm_term=ceej&utm_content=1&utm_campaign=20160601) that allows you to trigger a PR when a package gets updated. I'm assuming greenkeeper currently only checks every x seconds if a package has been updated, right? If so, then this would be an improvement.

**Comment by boennemann** [comment]
Hey @leo,

thanks for your feedback.
We are currently using the changes feed of npm's couchdb (https://skimdb.npmjs.com/), which already gives us real time capabilities.
npm hooks are a feature that we've been anticipating because it will make supporting private npm packages way easier for us.

While waiting for them we've developed our own workaround called [greenkeeper-postpublish](https://github.com/greenkeeperio/greenkeeper-postpublish), that we're currently beta testing. With the arrival of npm hooks we can now streamline that experience and make it way smoother for users.

Of course we'll have a very close look at what npm hooks offer us overall, and if we can improve the product experience switching over to them.

Best,
Stephan

**Comment by leo** [comment]
@boennemann Great to hear! Thanks for clarifying how it currently works.

**Comment by boennemann** [comment]
This went live with Greenkeeper 2. Closing this issue.
