### ISSUE TITLE
greenkeeperio-bot creates branch, but it does not create PR

### ISSUE THREAD

**Issue by mdreizin** [greenkeeperio/greenkeeper#217]
Currently I have a lot of created branches, but I don't have any PRs.

Does `greenkeeperio-bot` create PR?

https://github.com/mdreizin/webpack-config/branches
https://travis-ci.org/mdreizin/webpack-config/builds/137613796
https://travis-ci.org/mdreizin/webpack-config/builds/136881316

**Comment by finnp** [comment]
Hey @mdreizin,

yeah as you probably have figured out yourself, this was because travis wasn't activated for branches. Greenkeeper creates the branches for every new version, but if the version is covered by your version range it will only create a PR if the build fails. If it succeeds it will just delete the branch. Since your travis config was only running on the master branch, Greenkeeper is basically still waiting for the status to be reported.

But with your new config you should be fine 👍  Let us know if you have any more questions.

**Comment by mdreizin** [comment]
@finnp Thank you very much for the clarification ;)
