### ISSUE TITLE
Greenkeeper does not delete the branches that it creates

### ISSUE THREAD

**Issue by BenoitAverty** [greenkeeperio/greenkeeper#221]
Hello,

I just enabled greenkeeper on a repo I'm working on. It works great when submitting pull requests and I already love it.

However, I now have several branches for semver minor updates, and they are still there after a few hours. I thought Greenkeeper was supposed to delete them ?

I'm guessing it's because my travis-ci job only triggers on the master branch and so there are no build results for the branch that greenkeeper created.

Is there a way around that or will I have to manually delete the branches ?

Note : I don't want to build all the branches because the release process is part of the travis build.

Thanks in advance

**Comment by finnp** [comment]
Hi @BenoitAverty,

yes that is correct. You need to have travis enabled for the Greenkeeper branches. This is needed because if a new version is covered by your version range, we only create a pull request when the build fails. So not every greenkeeper branch results in a pull request. Some are just deleted as long as the build will pass.

I've seen that you whitelisted the greenkeeper branches. So it should work now 👍 

Feel free to reopen if this doesn't solve your problem or you have any questions.

**Comment by BenoitAverty** [comment]
Hello @finnp,

Thanks for your response. As you've seen, I updated the .travis.yml file and merged the new version into one of the branches created by greenkeeper. The build was triggered and passed but the branch is still there.

Can you confirm that I don't have anything else to do? I don't mind deleting these branches myself as long as it works in the future.

**Comment by finnp** [comment]
Yes, your setup looks right now. You'll just have to delete the existing branches.
