### ISSUE TITLE
Organization account support?

### ISSUE THREAD

**Issue by d6u** [greenkeeperio/greenkeeper#239]
I use greenkeeper for my personal use. I also want to use it for my company's Github organization (we are ready to pay the $50 even $100). But I don't want to mix my personal and company account together. It looks like greenkeeper will bind to a github user. Is there anyway not to bind to my own account, do I have to create a bot account on Github for my org?

**Comment by finnp** [comment]
Hello @d6u,

thank for your interest. Since our bot doesn't have access to your organisations private repositories, you would need to create your own GitHub bot account. Then you'll have to run `greenkeeper logout && greenkeeper login --private` with your bot account and do `greenkeeper update`. Then if you do `greenkeeper enable` on a repository, it will use your custom bot account for pull requests.

For your personal projects you could need to switch accounts then. You could simplify that by using changing your access tokens in `greenkeeper config`.

Would that work out for you?

Best,
Finn

**Comment by d6u** [comment]
Thanks @finnp. It turns our Github organization has legacy support for 3rd party apps, and update to new format will disrupt other apps. So we will put this on hold.
