### ISSUE TITLE
prefix commits updating dependencies with `fix: `

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#249]
We use [semantic-release](https://github.com/semantic-release/semantic-release) for all our packages, so we follow the angular commit conventions with the `fix:`, `feat:`, `chore:`, `BREAKING CHANGE:` etc conventions.

A problem that I’ve run into, especially with packages that are small and don’t have bug fixes or new features in a long time, is that while the dependencies get updated on GitHub, no new version gets released on npm. That leads to duplicated dependencies. Say `lodash` gets an update, that we use among many of our modules. If it is a dependency (not a devDependency), I want to release a new version to npm, so that an app using several of our modules will not end up loading different lodash versions.

Hope that makes sense? Basically my suggestion is this:

1. If the update is a devDependency, leave everything as is.
2. If the updates is a dependency, use the `fix: ` prefix instead of the `chore:` prefix

**Comment by albinekb** [comment]
We use an alternative to semantic-release, where we prefix every commit with an emoji (🍭 in the case of dependency updates)

Will this be customizable like described in #153?

**Comment by yoshuawuyts** [comment]
@gr2m yeah that'd be neat. When there's a hard update in the tree it would make sense to update the package anyway, if anything to prevent errors from accumulating - semantic versioning is not perfect, releasing sooner rather than later might help catch stuff (and yeah also solve the issues you laid out)

I'm :+1: on this change

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations.

With the new Greenkeeper this issue is resolved and you can try it out today: https://github.com/integration/greenkeeper
Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan

**Comment by yoshuawuyts** [comment]
@boennemann given that the new greenkeeper integration can operate on full projects, will it detect if a project is a node project? - wouldn't wanna get flooded with err messages; figured I'd ask before enabling it on 500 or so repos haha

**Comment by boennemann** [comment]
@yoshuawuyts It will simply ignore projects without a package.json present :)

**Comment by yoshuawuyts** [comment]
@boennemann radddddd, thanks! :sparkles:
