### ISSUE TITLE
Update permissions

### ISSUE THREAD

**Issue by piranna** [greenkeeperio/greenkeeper#250]
At this moment it's required collaborators to have admin permission on a repo so `greenkeeper` can work. Besides the fact I can't be able to find an option to give this permissions, I think this is a killer since they are only needed to enable the webhooks, not to create regular pull-requests. I'm starting to use in NodeOS a bot account to manage all the automatic tasks so my user profile (with administrator priviledges...) don't appear everywhere, and I'm able to use it to create pull-requests using my own module [buho](https://github.com/piranna/buho) (inspired by `greenkeeper` ;-) ), so I think it would be possible to make administrator to enable a project and later define another un-priviledged collaborator to do the pull-requests, maybe with a `delegate` command on the CLI or something... What do you think?

**Comment by boennemann** [comment]
Hey @AdriVanHoudt,

I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations.

With the new Greenkeeper this issue is resolved. You can grant permissions based on an organisations and even repository level. It is no longer required to grant us admin access.

You can try it out today: https://github.com/integration/greenkeeper
Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
