### ISSUE TITLE
Inconsistent Update Behavior

### ISSUE THREAD

**Issue by d3viant0ne** [greenkeeperio/greenkeeper#260]
Realistically 2 issues here.

![screen shot 2016-08-03 at 6 27 18 pm](https://cloud.githubusercontent.com/assets/8420490/17385549/0b6e8584-59a9-11e6-834b-35b0422849fe.png)

1.) Greenkeeper is evaluating `"grid-list": "2.0.0-alpha.4-3"` > `"grid-list": "2.0.0-alpha.6"` 

2.) And here is the really strange part, you would expect this behavior to be true for all of the material2 packages. For instance, `@angular2-material/icon`

![screen shot 2016-08-03 at 6 33 34 pm](https://cloud.githubusercontent.com/assets/8420490/17385667/cfd81ef8-59a9-11e6-937d-dd2aca5199a5.png)

Let me know if you need more information. Also thanks for saving myself and my team a ton of time on maintenance :)

**Comment by finnp** [comment]
Hey @d3viant0ne,

thanks for reporting this. The thing is that Greenkeeper is right about the evaluation of the versions. `2.0.0-alpha.4-3` is actually greater than `2.0.0-alpha.6` (see [semver spec](http://semver.org/#spec-item-11)):
```
> semver.compare('2.0.0-alpha.4', '2.0.0-alpha.6')
-1
> semver.compare('2.0.0-alpha.4.3', '2.0.0-alpha.6')
-1
> semver.compare('2.0.0-alpha.4-3', '2.0.0-alpha.6')
1
```

The reason for this is that numeric identifiers always have a lower precedence than non-numeric ones. And while `6` is numeric `4-3` is not. For it to be in line with the spec it would need to be `4.3`.

However as you noticed there was also something going wrong. This was because we didn't want to pin to prerelease versions. So we look for the first version that does not have a prerelase tag. In your cases there were none, so it ended up with a rather random prerelease version. In most cases this was `-alpha.4`, which is not greater than `-alpha.6`, so it didn't bump it, but in the one cast it found `-alpha.4-3` which seemed greater so you received a PR.

So far for the explanation of what happened ☺️ I will look into this, so that in the future this will pin to the latest prerelease version if the version specified is a prerelease as well.

However for you use case, Greenkeeper will still work unexpectedly.  Since if the next version is `alpha.6-1`, we will happily send you a PR this. After you'd merge it, you wouldn't get a `alpha.7` update though, only one for `alpha.7-1` -- Since we don't do downgrades.

I'd recommend that you switch to semver compatible prereleases by using `alpha.6.1` in the future. Then you will get Greenkeeper updates as expected.
