### ISSUE TITLE
Green CI builds get "breaks build" PR

### ISSUE THREAD

**Issue by Arcanemagus** [greenkeeperio/greenkeeper#262]
For some bizarre reason, although all the CI builds were sucessfull GreenKeeper is claiming the version breaks the build: 

* https://github.com/AtomLinter/linter-jshint/pull/319
* https://github.com/AtomLinter/linter-php/pull/193

**Comment by finnp** [comment]
Hello @Arcanemagus,

Your Travis and Appveyor config is set to only run on the master branch. However Greenkeeper creates new branches for new dependency versions and waits for the CI status to be reported. In your case Circle CI reported a failing status on that branch, so then the pull request was created. 

So you would need to add `- /^greenkeeper-.*$/` to the `travis.yml` and `appveyor.yml`, so that the services will run for the greenkeeper branches.

Part of the problem is also that we don't update the pull request when the CI status changed. So I'd recommend you to watch and vote on that issue: https://github.com/greenkeeperio/greenkeeper/issues/257

Let me know if you have any questions about this.

**Comment by Arcanemagus** [comment]
Ah ha! Good call on the previous failed builds, I hadn't manually restarted a build so I didn't think to check the history. It looks like for both of these the `apt-get -f install` step timed out and CircleCI _automatically_ restarted the build, so by the time I checked it a few hours later it was all green.

Btw, the configuration isn't the issue. We have dozens of repositories setup in that manner, the "only master" part makes it so it builds on the state after doing a merge of the changes back into master, instead of that merge _and_ the branch itself. None of these have had issues in the past, and in fact these two repos have had no issues with other dependency updates.

Thanks for the great service! I'm already subscribed to that issue 😉.
