### ISSUE TITLE
Merging together multiple pull requests

### ISSUE THREAD

**Issue by cchan** [greenkeeperio/greenkeeper#264]
When a dependency changes again while a greenkeeper pull request is up, it should edit the old pull request, by updating the title and description to reflect the total diff, and appending a commit.

**Comment by ranisalt** [comment]
I suggest closing the previous instead. Just had this issue with nyc, I accepted the PR updating to 8.0.0 before I saw there was a PR for 8.1.0 and the latter can't be merged now.

**Comment by boennemann** [comment]
Hey y'all and thanks for the feedback.

Greenkeeper doesn't want to make decisions for its users, but rather take chores away.
This is why we don't close pull requests, or change versions of them, before you have taken a decision yourself.
We don't know if you prefer "^8.0.0" over "^8.1.0" and we don't want to assume that it'll always be the same choice.

We will however take chores away from you. This means as soon as you merge 8.1.0 we will close 8.0.0 because it's a smaller version and therefor no longer relevant. If you merge 8.0.0 we'd close 8.1.0 because it's included in the same range.

Let's assume you have "^8.0.0" and "^9.0.0" open. If you merge 8.0.0 we'll rebase 9.0.0 so it'll be mergeable again.

I hope this addresses the problems you are mentioning sufficiently.


Best,
Stephan

**Comment by ranisalt** [comment]
Good point. Problem with me was that the issue for 8.1.0 was opened while I was merging 8.0.0 (I usually merge on the command line), so I really didn't see, but whatever as the range is the same.
