### ISSUE TITLE
Add ability to tell greenkeeper which commit status is CI

### ISSUE THREAD

**Issue by paultyng** [greenkeeperio/greenkeeper#268]
We have some commit status in our PR's that is not CI related (process related, code review, etc).  I'd like to exclude failures of those from failures of a greenkeeper PR so that it can delete ones in which the update is successful.  It doesn't seem like this is possible or maybe I'm misunderstanding how it reads success on a PR?

**Comment by paultyng** [comment]
I guess the other option is tell greenkeeper which commit status context's to ignore.

**Comment by boennemann** [comment]
Hey @paultyng,

thanks for your suggestions. May I ask in which way a Greenkeeper commit gets services other than CI to fail? We've always avoided the setting you're suggesting, because an updated package.json shouldn't possibly change anything other than the CI result. E.g. linting, coverage, etc. should not be affected by a package.json change, and therefor always keep passing.

It would be great if you could provide more detailed examples so we can better investigate this problem.

Thanks,
Stephan

**Comment by paultyng** [comment]
Sure, and again this may be my misunderstanding of how Greenkeeper works in relation to commit status, but we use [a system](https://github.com/paultyng/further-review) to enforce our PR process which sets commit status based on whether or not people have reviewed code (ie. signing off in a PR with 'LGTM').  There are [other systems](https://lgtm.co/) that do this as well.  So as soon as you open that PR, it may go to a `failure` commit status because its awaiting maintainer review.

**Comment by paultyng** [comment]
Here is an example PR: https://github.com/paultyng/further-review/pull/19

**Comment by boennemann** [comment]
Hey @paultyng,

Cool tool you got there 👍 
We check for the status of the branch, not the PR, where this guideline status shouldn't be present. E.g. we're using LGTM for [hoodie](http://github.com/hoodiehq) and Greenkeeper still works just fine with it.

I'd recommend to let further-review only set statuses on a PR, not on branches. Additionally you might want to use the yellow "pending" state if you're waiting for a maintainer, rather than setting it to red right away.

I hope this helps to resolve this problem. Let me know if you need more info, or still think we have to change Greenkeeper's behaviour.


Best,
Stephan

**Comment by boennemann** [comment]
![inrange_4](https://cloud.githubusercontent.com/assets/908178/17743524/49c66eb8-64a4-11e6-8d93-1b983635d947.png)

A visualisation from my Cascadia talk. Should make it easier to understand :)

**Comment by paultyng** [comment]
Got it, thanks, yeah, I only touch PR's currently so should be good.

**Comment by boennemann** [comment]
Great, thanks for reaching out 👍
