### ISSUE TITLE
Notify only about dependencies not devDependencies

### ISSUE THREAD

**Issue by simov** [greenkeeperio/greenkeeper#27]
:wave: 

Is there a way to configure the client to check only for `dependencies`? I noticed that in [request](https://github.com/request/request) you service can get really annoying just because we have a lot of `devDependencies` that get constantly updated.

**Comment by boennemann** [comment]
Hey @simov,

we are working on adding a more fine grained control to Greenkeeper. In the meantime you could add back version ranges to your devDependencies, because Greenkeeper will only send you a pull-request if the new version doesn't satisfy the existing range.

Best,
Stephan

**Comment by simov** [comment]
That's a nice tip, thanks @boennemann!

**Comment by boennemann** [comment]
Hey @simov,

There are bad news: We have removed this from our immediate to do list.
And there are good news: We think we've found a better way to solve the root of the problem

We think the actual problem you and others reported is that all these pull requests can get overwhelming and quickly become too noisy – a valid complaint.

We've just now deployed a new feature. You can now add version ranges to your dependencies again and we will treat them right.

For new versions inside the existing range you’ll get pull-requests **only if the update breaks your build**. We are doing this by only creating the branch and then waiting for results from your CI. If it passes the branch gets deleted again, if it fails however the pull requests gets opened, because it should definitely have your attention.

```diff
-  "underscore": "^1.6.0"
+  "underscore": "^1.7.0"
```

When a new version is outside of your existing range you’ll just get the pull request right away.

```diff
-  "lodash": "^3.0.0"
+  "lodash": "^4.0.0"
```

You can now define the level of "noise" per dependency by using "^", "~", or pin.
We hope you like this change and would be very happy to get your feedback on this.

Best,
Stephan

**Comment by mrchief** [comment]
After using it for some time, I can say that it still gets noisy. I simply don't care about `devDependencies`. I'll update them whenever I get a chance, I just don't need GK to keep opening PRs for new versions. 

Why is it so hard to add a flag to ignore dev deps?
