### ISSUE TITLE
Question: Checking in intervals?

### ISSUE THREAD

**Issue by amilajack** [greenkeeperio/greenkeeper#291]
Greenkeeper checks my repo too often. Is there a way to reduce the frequency at which it checks?

**Comment by finnp** [comment]
Hey @amilajack,

we do send pull requests once the dependencies have a new update. Is your problem that you get too many pull requests?

**Comment by amilajack** [comment]
Yup!

**Comment by paralin** [comment]
Why is this a problem?

**Comment by amilajack** [comment]
Right now it checks every time a new dependency comes out. A new PR has to be made for each new dependency. That gets frustrating after a while.

If it could be configured to work in intervals, users could handle all the new dependencies in one PR.

**Comment by paralin** [comment]
This is for a reason, though. One dependency could break your tests, and you would want to address the breaking changes in a specific branch (the greenkeeper branch). You can't tell what broke the tests if you have 10 things updated in one pr. Same goes for bisecting the git tree, if something broke and you try to do a git bisect to figure out what broke it, it'll be impossible to tell which dependency update did it.

**Comment by amilajack** [comment]
I see. Thanks for explaining

**Comment by jmaupetit** [comment]
Hi there! It's a rather old issue, but I have the same feeling as @amilajack :wink: 

> it'll be impossible to tell which dependency update did it

Unless greenkeeper makes a commit per dependency update in the same branch and pushes sequentially commits from that branch (so that the CI runs on every commit) and then opens a PR. That's what [pyup](https://pyup.io) does and it's really comfortable as we can define the update schedule.

WDYT?
