### ISSUE TITLE
Only show node projects in web app

### ISSUE THREAD

**Issue by leo** [greenkeeperio/greenkeeper#295]
Instead of simply showing all repos, we should hide the ones that don't even have a package.json.

**Comment by boennemann** [comment]
Hey @leo,

this indeed sounds like a good idea.

We're hard at work to migrate to GitHub integrations and with it the whole enabling mechanism will slightly change, so that this isn't even necessary anymore. So we'll rather hurry with that and hope to get rid of it, rather than implementing your suggestion now.

Thanks for understanding :)

Best,
Stephan

**Comment by leo** [comment]
@boennemann Nice! Thanks for that. 😄
