### ISSUE TITLE
Including the release notes in the PR is sometimes very spammy

### ISSUE THREAD

**Issue by ide** [greenkeeperio/greenkeeper#299]
The example at hand is the react-native repo which has release notes of the form:

- A description of a new feature - @[authorOfTheFeature]

Release notes don't notify people on GitHub but when Greenkeeper pulls them in it notifies everyone. So if 20 authors are credited in release notes and Greenkeeper sends out 50 automated PRs, that's 1000 notifications that none of those 20 authors want.

One idea is to strip the @ from mentions and then the important part of the release notes would still come across.

**Comment by finnp** [comment]
Hey @ide,

can you point me to an example? We already replace GitHub links (including at-mentions) with our own redirect-server, so that GitHub doesn't pick them up as mentions. Which should have the same effect as stripping them.

Best,
Finn

**Comment by terribleben** [comment]
Posting an example at the request of @ide!

Here are the react native release notes for 0.34: https://github.com/facebook/react-native/releases

All of those @ handles were turned into callouts in the resulting greenkeeper notification:
![image](https://cloud.githubusercontent.com/assets/1316332/19044471/4c6ea0bc-8949-11e6-9ce6-56fdaabc53ab.png)

I got a lot of emails as a result:
![image](https://cloud.githubusercontent.com/assets/1316332/19044396/f2c61004-8948-11e6-8793-5d469a55fc81.png)

**Comment by finnp** [comment]
Hey @terribleben,

thank you for posting this. It seems to be a bug, where some names somehow don't get converted. Here's a reference pull request: https://github.com/este/este/pull/1159

We will look into this.

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations.

With the new Greenkeeper this issue is resolved and you can try it out today: https://github.com/integration/greenkeeper
Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
