### ISSUE TITLE
Credentials should be stored encrypted

### ISSUE THREAD

**Issue by thomblake** [greenkeeperio/greenkeeper#300]
Currently, github credentials are stored in plaintext in the Cloudant database. If they were stored encrypted, then Greenkeeper users would be protected against any attacks that steal data from Cloudant.

This is a blocker for getting PagerDuty to adopt Greenkeeper.

**Comment by boennemann** [comment]
Hey Thom,

we don't store credentials (as in user & password) anywhere, because we never even get them.
We're using GitHub's oAuth flow to obtain an access token, that allows us to perform actions on the behalf of the user, but only scoped to the actions they've granted.

Unlike webservices who only need/should store their own users password in an encrypted/hashed fashion we have to have access to the tokens in plain text, in order to authorise our requests to GitHub.

We could of course encrypt our tokens in a two way fashion using e.g. AES, but we think that this wouldn't significantly improve the security. We can only protect the AES secret as much as we can protect our database secrets. If an attacker is able to get our database secrets, they'll also be able to get our encryption secret.

This leaves us with security holes with our database provider. Of course this is something that can never be fully ruled out. We decided to go with Cloudant, because we think that their industry leading expertise in hosting and securing CouchDB installations is the best we can get here.
Should there be a security breach with them a two-way encryption would of course help.
Should we get to know of a security breach with Cloudant we will use the oAuth application's functionality to revoke all of our tokens immediately.
Revoking tokens is something that individual users can do at any time, if they think something odd is happening. None of GitHub's documentation or guides for using oAuth applications recommends or asks integrators to perform such an additional encryption step.

If this keeping you from using Greenkeeper right now I'm sorry to hear that, but of course we understand.

We're currently in the process of migrating Greenkeeper to [GitHub Integrations](https://developer.github.com/early-access/integrations/authentication/), which are no longer based on permanent tokens, but only ones who will expire after an hour. With our new architecture we plan to never even store tokens anywhere at all.
We're currently using all our engineering resources to finish this migration, so implementing a two way encryption for oAuth tokens is something we will not do anymore.

The next time you reach out to us via private communication channels to talk about security we would really appreciate if you could just stick to this channel, rather than moving your reply to our public issue tracker, containing information that was originally intended for you only.

Thank you,
Stephan

**Comment by thomblake** [comment]
Thanks for the update! Is there another place where we can track the progress of the migration to GitHub Integrations?
