### ISSUE TITLE
does greenkeeper have support for private npm modules?

### ISSUE THREAD

**Issue by kellyrmilligan** [greenkeeperio/greenkeeper#302]
we have private repos with private npm modules, does the paid plan support this?

**Comment by boennemann** [comment]
Hey @kellyrmilligan,

we're currently supporting scoped npm packages with our postpublish hook. https://github.com/greenkeeperio/greenkeeper-postpublish

Enabling the repository of the scoped package via CLI automatically adds this hook.

In order to be able to get PRs from that package you need to run `greenkeeper npm-access --org <your-org>`.
Verify that it works with `greenkeeper npm-verify --org <your-org>.

Best,
Stephan

**Comment by mbrevda** [comment]
Is this still the way for scoped/private modules?
