### ISSUE TITLE
Commit for new package version, but PR was not created

### ISSUE THREAD

**Issue by LarsHassler** [greenkeeperio/greenkeeper#307]
**Repo:** remobid/js-core _(private repo)_

The cross-env package was update fairly quickly by to versions. For both there was a commit created by greenkeeper, but for some reason the second update was not attached to a pull request.

_Both builds inside circleci_
<img width="1062" alt="screen shot 2016-10-05 at 08 25 00" src="https://cloud.githubusercontent.com/assets/1721016/19103205/c62df294-8ad5-11e6-9728-173474ff5c63.png">

_The commit with the pull request for the older version:_
<img width="976" alt="screen shot 2016-10-05 at 08 25 27" src="https://cloud.githubusercontent.com/assets/1721016/19103282/2e565f00-8ad6-11e6-86cc-f64a8a0a4156.png">

_The commit with no pull request for the newer version:_
<img width="979" alt="screen shot 2016-10-05 at 08 25 39" src="https://cloud.githubusercontent.com/assets/1721016/19103289/3e4cd6fa-8ad6-11e6-9e55-8d82e1eaeefd.png">

If there is anything i can provide additionally to help find the problem, just let me know.

**Comment by boennemann** [comment]
Hey @LarsHassler,

suspecting that you have defined the dependency to cross-env something with something like ^3.0.0 the 3.1.1 commit wasn't turned into a PR because the CI build passed.

Greenkeeper only opens pull requests when an in-range update fails (e.g. 3.1.0 failed), or for out of range updates. https://blog.greenkeeper.io/announcing-real-time-dependency-break-detection-for-greenkeeper-4f7558c10d77

If you haven't defined the dependency with a version range I'm happy to reopen and investigate.

Thanks for using Greenkeeper,
Stephan
