### ISSUE TITLE
PR within private repo was not created by the greenkeeperio-bot, but in my name

### ISSUE THREAD

**Issue by LarsHassler** [greenkeeperio/greenkeeper#309]
For a private repo of an organization the pull request ist created in my name (i'm the one approved who the access to the organization).

For my own public repository everything works fine.

Is this a constraint for private org repos or a bug?

## _The pull request by greenkeeper, which was created in my name:_
<img width="671" alt="screen shot 2016-10-05 at 09 12 14" src="https://cloud.githubusercontent.com/assets/1721016/19105106/9278e958-8ae0-11e6-8ca9-86c7735a445c.png">

## _The correct pull request within the public repo:_
<img width="459" alt="screen shot 2016-10-05 at 09 39 02" src="https://cloud.githubusercontent.com/assets/1721016/19105147/c7aa8fe6-8ae0-11e6-8a2d-62e35d579a5c.png">

**Comment by boennemann** [comment]
Hey @LarsHassler,

thanks for reporting this.
Unfortunately this is a constraint for private repos, because the Greenkeeper Bot doesn't have access to your repo and can't open pull requests on it.

For the time being we recommend using a bot account for private repos, **but** with [GitHub Integrations](https://developer.github.com/early-access/integrations/) on the way (and we're hard at work to make use of them asap) I'm happy to report that this problem will soon be gone. This is because Integrations can act on their own behalf, and don't need to act as a user.

I'll keep this issue open for other to find and discuss and will happily close with the launch of our GitHub integration.

Thanks again,
Stephan

**Comment by LarsHassler** [comment]
Thanks for the quick reply.

I'd thought so, but found no other issue or any mention in the faq.

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations.

With the new Greenkeeper this issue is resolved and you can try it out today: https://github.com/integration/greenkeeper
Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
