### ISSUE TITLE
Greenkeeper creates a branch only to delete it straight after

### ISSUE THREAD

**Issue by CodeTheory** [greenkeeperio/greenkeeper#317]
This has been happening for a while now. I've been busy so I haven't had a chance to look into it, but I can't figure out a way to fix it. It's happening over at Kap and Hyper.app.

![image](https://cloud.githubusercontent.com/assets/1695613/19566442/359eb6fa-96e2-11e6-91e1-1207fa34b030.png)

cc/ @leo

**Comment by leo** [comment]
Same for all @zeit repos and my personal ones!

**Comment by boennemann** [comment]
Hey @CodeTheory, hey @leo,

Greenkeeper deletes the branch because Travis passes and the version is included in your version range. There is no need for us to open a PR (, or for you to merge one). You will automatically get the version as defined via the range :)

Best,
Stephan


https://blog.greenkeeper.io/announcing-real-time-dependency-break-detection-for-greenkeeper-4f7558c10d77#.9w3m3h7ac
https://greenkeeper.io/faq.html#github-activity

**Comment by leo** [comment]
Ahhhhhhhhhhh! Thanks for the info.
