### ISSUE TITLE
Bot commits to an invisible branch ?

### ISSUE THREAD

**Issue by Gomah** [greenkeeperio/greenkeeper#330]
Hello greenkeeper team,

First of all, thank-you for this service & the efforts you are putting in this project.

Since yesterday, I'm encountering a very weird issue, the greenkeeper bot push into an "invisible" branch:

<img width="882" alt="screen shot 2016-11-03 at 10 05 18 am" src="https://cloud.githubusercontent.com/assets/2362138/19952059/7055d272-a1b6-11e6-9649-8280ea5a1442.png">

After fetching everything, all these branches are still invisible in the repository (happens on private & public repositories), I double checked & greenkeeper has the correct rights access.

I can still find the commit but cannot create a pull-request:

![screen shot 2016-11-03 at 11 13 56 am](https://cloud.githubusercontent.com/assets/2362138/19952271/23dc7d4a-a1b8-11e6-8402-8add2f3a9dfa.png)

Any thoughts?
Cheers

**Comment by finnp** [comment]
Hello @Gomah,

this happened because the updates were in-range updates. So for example `aws-sdk@2.6.14` is already covered by your version range `^2.6.12`. So we only created a branch with the new version to see if it broke something. Since it didn't, everything seemed fine, so the bot automatically deleted the branches again.

If the status would be failing, we would create an issue on your repository to leat you know about it.

Does this make sense?

Best,
Finn

**Comment by Gomah** [comment]
Perfect sense, thanks for the clarification ;)
