### ISSUE TITLE
Integration triggered "get started" PR after version updates

### ISSUE THREAD

**Issue by danez** [greenkeeperio/greenkeeper#332]
I just got a PR with the title "Update dependencies to enable Greenkeeper"
But greenkeeper with integrations is already running since a week and was submitting PRs for versions successfully before.
And before that greenkeeper was running for a long time in non-integration mode.

https://github.com/researchgate/webpack-watchman-plugin/pulls

**Comment by boennemann** [comment]
Hey @danez,

I'm super sorry this happened and thanks for letting us know.

The GitHub Integrations API was recently changed by GitHub, so that the endpoint that listed all repositories of an installation was paginated, where it previously wasn't.
As GitHub Integrations are in beta, this happened without any prior notice to us.
We were receiving a lot of webhooks for repositories that we hadn't synced to our database, because of this pagination problem – which is why we noticed.

To fix this problem on our side we decided to rerun the installation events, after adding pagination support, so that the repositories would get properly synced up again.

It looks like we made the bad mistake, to not check for previously enabled repositories, while doing so. This means all repositories that were previously enabled, but since then  became out of sync again, received a duplicate "get started" PR.

As your repository is already enabled you can safely close that PR. We're rolling out new badges, and you can use them to verify whether a repository is enabled: `![Greenkeeper Badge](https://badges.greenkeeper.io/researchgate/webpack-watchman-plugin.svg)`
![Greenkeeper Badge](https://badges.greenkeeper.io/researchgate/webpack-watchman-plugin.svg)

It is currently night time here, but I will see tomorrow if we can detect the repositories affected and somehow clean this up automatically.

Sorry again,
Stephan
