### ISSUE TITLE
Newly enabled repos are ignored by integration

### ISSUE THREAD

**Issue by FredyC** [greenkeeperio/greenkeeper#336]
I've installed the new integration today for our [organization](https://github.com/BlackDice/) and enabled only couple of repos first. Now I wanted to add another one, but PR was never created. I tried to add the [new badge to README](https://github.com/BlackDice/nome/tree/greenkeeper), but it says "not found".

**Comment by FredyC** [comment]
Not sure if that badge actually works or I am using it somehow badly (case sensitive?). I tried to add it to [other repo](https://github.com/BlackDice/lill/tree/greenkeeper) which already got greenkeeper PR today and was merged. It also says "not found".

**Comment by finnp** [comment]
Hey @FredyC,

currently we only send a pull request to your repository if there is anything to update. If everything is up-to-date we enable the repository right away.

The badges were not working because they are currently case-sensitive:. So using https://badges.greenkeeper.io/BlackDice/nome.svg works. We're going to change them to be ignore casing :)

Best,
Finn

**Comment by FredyC** [comment]
@finnp Awesome, thanks. Badge is working now for both projects.
