### ISSUE TITLE
Respect existing versioning scheme

### ISSUE THREAD

**Issue by lpinca** [greenkeeperio/greenkeeper#344]
Most of the projects I contribute to use the [x-ranges](https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-) versioning scheme for dependencies. For example:

```json
{
  "dependencies": {
    "request": "2.78.x"
  }
}
```

When Greenkeeper sends an update it changes the versioning scheme to [tilde-ranges](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1):

```json
{
  "dependencies": {
    "request": "~2.79.0"
  }
}
```

This is correct but is there a way to tell Greenkeeper to use the original versioning scheme (`2.79.x`)?

**Comment by finnp** [comment]
We might improve on this in the future. For now we are changing x-version ranges to the equivalent tilde/caret because if we would like to update `2.79.x` to test  `2.79.1` we have to switch to tildes because otherwise it could get `2.79.0.` from the cache during installation. 

I know in your case that wouldn't be a problem. For now if you want to keep using x-ranges I'll recommend editing the range back in the pull request and then merge it.

**Comment by lpinca** [comment]
> For now if you want to keep using x-ranges I'll recommend editing the range back in the pull request and then merge it.

Yeah, that's what I'm doing now. Thanks.
