### ISSUE TITLE
greenkeeper/verify never completes

### ISSUE THREAD

**Issue by Charlotteis** [greenkeeperio/greenkeeper#381]
On every PR I open in github.com/charlotteis/hottake, there is a 'greenkeeper/verify' status check that never ever completes. How do I get rid of it? I'm not sure if greenkeeper is enabled on my package now, despite letting the integration work on all of my repos.

<img width="824" alt="verifygreenkeeper" src="https://cloud.githubusercontent.com/assets/542140/23029282/e473d4e4-f461-11e6-8f17-09952d3addc3.png">

Edit: I uninstalled and reinstalled the integration, I will see if that works.

**Comment by boennemann** [comment]
Hey @Charlotteis,

thanks for reaching out :)
this is caused by `greenkeeper/verify` being set as a required status.
This should be deactivated because this status type won't be present on all PRs, only the ones from Greenkeeper. As Greenkeeper only knows about its own PRs all others will never get any status flag from it.

You can deactivate the required state here: https://github.com/charlotteis/hottake/settings/branches/master

Best,
Stephan

**Comment by Charlotteis** [comment]
*facepalm*

Thank you Stephan 💖

**Comment by paibamboo** [comment]
It's never complete for the pr created by greenkeeper itself too. is that normal?

**Comment by Realtin** [comment]
@paibamboo what is the name of the repository that this is happening to?

**Comment by paibamboo** [comment]
@Realtin It's our organization's private repo. Here are some screenshots.

![image](https://user-images.githubusercontent.com/13611391/30802384-86b52eb8-a210-11e7-8bb5-1af6ce1d7842.png)

![image](https://user-images.githubusercontent.com/13611391/30802406-a614fb58-a210-11e7-93b2-108ac5c9446d.png)

**Comment by Realtin** [comment]
@paibamboo It is not normal, is this the inital pull request?
With the org/name of the repo I can investigate in our error logs and reset the repository if you like, so you would get a new inital pull request.

**Comment by paibamboo** [comment]
@Realtin The org/name is crazyfactory/shop-webapp-components. No it's not an initial pull request.
