### ISSUE TITLE
[Features] Fine-Tuning

### ISSUE THREAD

**Issue by mattdesl** [greenkeeperio/greenkeeper#39]
This is a really cool project. I hope you don't mind me putting down a few ideas on how I think it could be improved for other use cases!

- Some modules, like `watchify`, are highly dependent on or lockstepped to another module, like `browserify`. However, it doesn't matter so much that its other dependencies are being updated. It would be good to be able to only enable greenkeeper on a specific set of dependencies within a module.
- It would be nice to avoid the pinning of dependencies. This way I can reduce commit/version clutter and just stick to patching when a Greenkeeper PR + Travis fails.
- It would also be nice to only listen for "major" version changes (or some other specifier)
- It might be nice to "batch" PRs or provide a "weekly digest" sort of system. It's a bit overwhelming when you have many modules, each with many dependencies.

Thanks for the tool! :tada:

**Comment by boennemann** [comment]
Hey @mattdesl, 

thanks for the great feedback.

I'm happy to tell you that we're already working, or planning on working on these features. We will roll them out over the coming days and weeks.

Best,
Stephan

**Comment by boennemann** [comment]
Hey @mattdesl,

There are bad news: We haven't quite implemented every single bit of your feature requests.
And there are good news: We think we've found a better way to solve the root of the problem

We think the actual problem you and others reported is that all these pull requests can get overwhelming and quickly become too noisy – a valid complaint.

We've just now deployed a new feature. You can now add version ranges to your dependencies again and we will treat them right.

For new versions inside the existing range you’ll get pull-requests only if the update breaks your build. We are doing this by only creating the branch and then waiting for results from your CI. If it passes the branch gets deleted again, if it fails however the pull requests gets opened, because it should definitely have your attention.

```diff
-  "underscore": "^1.6.0"
+  "underscore": "^1.7.0"
```

When a new version is outside of your existing range you’ll just get the pull request right away.

```diff
-  "lodash": "^3.0.0"
+  "lodash": "^4.0.0"
```

You can now define the level of "noise" per dependency by using "^", "~", or pin.
We hope you like this change and would be very happy to get your feedback on this.

Best,
Stephan

**Comment by AdriVanHoudt** [comment]
So I can use 3.0.x and greenkeeper will test in the background if tests pass on new patches and if not do a PR?

**Comment by boennemann** [comment]
@AdriVanHoudt We're currently not supporting the `.x` syntax, but for `~3.0.0` that's exactly how it works now :)

**Comment by AdriVanHoudt** [comment]
Oh so if the tests fail you will do a PR with pinned version?

**Comment by boennemann** [comment]
@AdriVanHoudt We'll pin if you're using another range than "^" or "~". Otherwise we reuse what is already there.

**Comment by AdriVanHoudt** [comment]
So .x will pin?
