### ISSUE TITLE
Is possible to let greenkeeper to make PR base from develop branch? 

### ISSUE THREAD

**Issue by yongpingchen** [greenkeeperio/greenkeeper#396]
In my project, I make CI to publish npm package from master build. However, PR made by greenkeeper is always from master branch. I am wondering whether to make greenkeeper to create PR based from other branchs, like develop.

**Comment by Arcanemagus** [comment]
From the [FAQ](https://greenkeeper.io/faq.html#branches) this isn't currently possible, but it's something they are planning for the future.

**Comment by finnp** [comment]
Basically you could only use your `develop` branch as the default branch on github (repository settings), because that is currently the branch we are using.

**Comment by hypery2k** [comment]
are there plans to support develop branch?

**Comment by rmehner** [comment]
> are there plans to support develop branch?

We already support that, if `develop` is set as your default branch.

**Comment by evereq** [comment]
For our projects, we prefer to not set `develop` as default branch for multiple reasons (e.g. so that everyone sees/clones stable `master` when visiting the project). But we still want to get PR requests from greenkeeper into `develop` branch, not `master`... 

I wonder how others solve that today (Gitflow is very popular I think) and how hard to add such configuration option to greenkeeper?
