### ISSUE TITLE
Greenkeeper does not do anything after it's enabled

### ISSUE THREAD

**Issue by msiegenthaler** [greenkeeperio/greenkeeper#418]
I just enabled greenkeeper on a private repo (organization linkyard). It did create an initial branch and after the build failed also an initial PR for it. But after I successfully merged this PR (after adding an additional commit to it), I did never hear from it.
The initial PR was merged on Friday, and there are serveral dependencies that were updated since then. Do I need to wait longer or did I do something wrong?

I case it's relevant: our project specifies all dependecies using exact versions in the `package.json` (e.g. "1.3.4", not "^1.3.0") and we also have a `yarn.json` (which we will update from the package.json using the CI).

**Comment by mehdivk** [comment]
Same problem here. Our private repo was using GreenKeeper happily for some time but then we noticed that we are not getting any more PRs from GreenKeeper due to changes in the billing model of GreenKeeper and introduction of GreenKeeper 2. Anyway, I added the cc information and didn't see any PR from GP despite the fact that some of deps were already outdated. I removed the integration and add it again and saw a new branch with deps updated immediately (CI failed due to some breaking changes) but didn't get a PR from GP either an issue.

**Comment by msiegenthaler** [comment]
btw: the greenkeeper badge is green and shows "Greenkeeper enabled", so it seems to be enabled. Still no branch or pull request created and more dependencies have new versions available.

**Comment by mehdivk** [comment]
@msiegenthaler from Greenkeeper FAQ page:

> I ENABLED A REPO, BUT NOTHING’S HAPPENING / DELETED BRANCHES
This might be because the dependency updates are within your specified ranges, and not breaking your tests. So there’s no point in bothering you with a PR, since everything still works.
You’ll only receive pull requests when an in-range dependency breaks your build, or when a dependency updates outside your specified range.

**Comment by msiegenthaler** [comment]
No branches are created by greenkeeper so no builds do happen. Also we don't have dependendy ranges.

For example I have this dependency declared in my package.json: `"apollo-client": "1.2.0",`
The newest version of this is `1.2.2` (as per https://www.npmjs.com/package/apollo-client).

Shouldn't that trigger at least a build and - from my understanding - also a PR?

I have this section in my package.json because I don't want to update some dependencies at the moment:
```
  "greenkeeper": {
    "ignore": [
      "react-router",
      "react-router-redux",
      "@types/react-router",
      "@types/react-router-redux"
    ]
  },
```

**Comment by janl** [comment]
Hi @msiegenthaler @mehdivk We’re looking into this.

@mehdivk can you share the org and repo this is happening on? You can use support@greenkeeper.io if you don’t want to make this public.

Best
Jan
—

**Comment by janl** [comment]
Hi, this should be fixed, please re-open if you see this again.

Thank you for your patience!
