### ISSUE TITLE
Update package-lock.json if exists (npm5)

### ISSUE THREAD

**Issue by tuananh** [greenkeeperio/greenkeeper#459]
If package-lock.json exists, update that as well. Otherwise, it will have no effect with node 8 (default shipped with npm5).

**Comment by gr2m** [comment]
we have a separate package for that: https://github.com/greenkeeperio/greenkeeper-lockfile, does that work for you?

**Comment by tuananh** [comment]
Thanks.

Btw, I'm a bit curious. Why doesn't greenkeeper do it automatically by default?

**Comment by gr2m** [comment]
doing it automatically is where we want to get, but ít’s complicated :tm: right now we need the script to run on your CI, it won’t work on the Greenkeeper servers, here is some more info: https://blog.greenkeeper.io/greenkeeper-support-for-lockfiles-9d9c282efcbe

**Comment by thomblake** [comment]
@gr2m Why won't it work on the Greenkeeper servers?

**Comment by ArmorDarks** [comment]
I assume it is because Greenkeeper need to run `npm install` with CI's environment first to get `package-lockfile.json` output. But it can't do that. It just creates PRs.

Add to that the fact, that differnt NPM versions outputting locfkile with slightly different ordering, and you're quite screwed up.

**Comment by janl** [comment]
Yes, for now we have to rely on your CI for this.

**Comment by janl** [comment]
Announcing native lockfile support: https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0
