### ISSUE TITLE
Manual webhooks setup, removes admin scope

### ISSUE THREAD

**Issue by boennemann** [greenkeeperio/greenkeeper#46]
This is technically doable, but requires some extra implementation bits to keep it secure.
Worthwhile feature for sure.

**Comment by phillipj** [comment]
Any progress on this by any chance? We're struggling with getting greenkeeper up-n-running on https://github.com/nodejs/nodejs.org/issues/377 and would really appreciate if we could add these webhooks manually.

**Comment by bripkens** [comment]
I'd also really like to see this feature land. I am struggling because greenkeeper requires a lot of permissions (write access to all public repositories is *a lot* to ask). Being able to setup webhooks manually and being able to avoid these broad permissions would be great.

Now that I am writing this: Why does greenkeeper need write access to repositories? I can understand the webhooks part…

**Comment by Charlotteis** [comment]
Having this would be great. I am a member of several organisations that let anything have access to all their things. I don't want greenkeeper to have access to 100s of repositories in my orgs when all I want to do is add greenkeeper to a personal project. Having a webhook would be great.

I know this will be implemented and am not asking anyone to rush, just giving an anecdote :)

**Comment by boennemann** [comment]
This landed with `greenkeeper@2.13.0` https://github.com/greenkeeperio/greenkeeper/releases/tag/v2.13.0.

Details: https://greenkeeper.io/manual-webhooks.html

Thanks for your patience.

**Comment by krystophv** [comment]
Is there some way to set up the new version of Greenkeeper without granting admin scope by manually setting up the webhooks?
