### ISSUE TITLE
FR: opt out of devDep updates

### ISSUE THREAD

**Issue by remy** [greenkeeperio/greenkeeper#47]
Short version: It would be useful to opt-out of devdeps.

Slightly longer version: There's usually a reason why I pin my devDeps to specific versions, and as much as I love what Greenkeeper is doing, most of the PRs on the project I'm trying it out on are the devDeps which I have to close.

A specific example is that I use tap-spec@2 instead of latest due to a bug in v3 through v5...

<3

**Comment by boennemann** [comment]
Hey @remy,

thanks for the feedback. I see why this is useful, but so far we've been shying away from a general opt-out of entire categories, because we're making a promise of letting you know when there is a problem immediately and that can't be true if you opt-out of an entire category per-se. 

There are definitely valid cases where you pin down a certain dependency and we're thinking of a good way to support that. Currently there is a "hidden feature" (i.e. things might change, not documented yet) where you can add an `"ignore"` array to your `"greenkeeper"` field in the `package.json` and we won't send you PRs for these dependencies.

```json
"greenkeeper": {
  "ignore": ["tap-spec"]
}
```

I hope that helps for now :)

I'm closing this in favor of https://github.com/greenkeeperio/greenkeeper/issues/27

Best,
Stephan
