### ISSUE TITLE
Greenkeeper doesn't seem to open pull requests on my repo, only creates and deletes branches

### ISSUE THREAD

**Issue by jankeromnes** [greenkeeperio/greenkeeper#476]
It's the second time something like this happens for our project https://github.com/JanitorTechnology/janitor, a branch is created and instantly deleted by greenkeeper, but no pull request in sight.

Our github IRC bot said this:

> 15:33:20 <github> [janitor] greenkeeper[bot] created greenkeeper/fast-json-patch-2.0.4 (+1 new commit): https://git.io/v7U6d
> 15:33:20 <github> janitor/greenkeeper/fast-json-patch-2.0.4 8a1f0bb greenkeeper[bot]: chore(package): update fast-json-patch to version 2.0.4
> 15:34:44 <github> [janitor] greenkeeper[bot] deleted greenkeeper/fast-json-patch-2.0.4 at 8a1f0bb: https://git.io/v7Uif

The commit it still there if you know its SHA, but it would be nice if greenkeeper actually created a pull request for it (to trigger tests, and for convenient merging). I know it usually does (and it did for the very first change to the README, but not since).

**Comment by gr2m** [comment]
Hey Jan,

this is Greenkeeper’s [Announcing “Real Time Dependency Break Detection”](https://blog.greenkeeper.io/announcing-real-time-dependency-break-detection-for-greenkeeper-4f7558c10d77#.9w3m3h7ac) :) Creating a branch triggers the CI on your tests, when test pass and the update of the package is _within_ the range defined in your package.json, then we delete it right after because the new version gets installed automatically. But if it breaks, we create an issue informing you that a new version within your defined range for XYZ is breaking your tests so you can have a look at it.

We only create pull requests for out-of-range updates.

Does that make sense?

**Comment by jankeromnes** [comment]
Aha, thanks, that does make sense. Is there a setting for forcing pull requests even for in-range updates?

**Comment by gr2m** [comment]
no, but you can use in fixed version numbers in your package.json by removing the `~` or `^`, would that be helpful already? 

Updating the version numbers has no effect, the new versions are within the range and will get installed automatically when you run `npm install`

**Comment by jankeromnes** [comment]
Thanks a lot for your quick and very helpful replies! 👍
