### ISSUE TITLE
Greenkeeper Hook Endpoint Responds with HTTP 413 when Updating a npm Package

### ISSUE THREAD

**Issue by DaRaFF** [greenkeeperio/greenkeeper#504]
As described in the initial pull request of greenkeeper 2 I tried to register a hook for private npm repositories with 

`wombat hook add @<package>/<name> https://hooks.greenkeeper.io/npm/<id> <token>`

After publishing a new version at npm I checked the HTTP Response with wombat. `wombat hooks ls` responded with a HTTP 413 status, which means that the request size was too big.

In our private repository we have a lot of stuff and the size of the package.json/shrinkwrap is around 300kb (I assume this will be sent to greenkeeper). I guess this is too much.

Could you please make the accepted request size of the hook endpoint bigger (`https://hooks.greenkeeper.io/npm/<id>`)?

**Comment by gr2m** [comment]
Thanks for opening the issue @DaRaFF! It’s the first time the issue was brought up so far so we can’t make it an immediate priority on our side, but you could help us figuring out the problem.

We don’t configure the allow max size at this point, by default it’s 1048576 bytes, which is 1MB (See https://hapijs.com/api, search for `maxBytes`).

I’m not familiar with the exact payload we receive from npm, but I think we only the package.json file.

If you could help us with some research around this, that’d be great. The route itself is defined at https://github.com/greenkeeperio/hooks/blob/dccb6aa9df3d076216b8937708f323b131b1fbb7/lib/npm-event.js#L13-L23, the tests are in `test/npm-test.js`. I’ve just created a PR to update the repository’s test setup, maybe use that as your base. Note that you need node 8 and Docker to be running

https://github.com/greenkeeperio/hooks/pull/6

Please let me know if you have any further questions and thanks a lot for your help 💐

**Comment by DaRaFF** [comment]
@gr2m thank you very much for fixing this issue! I still get a HTTP 413 status from the greenkeeper API, so I assume this fix has not been deployed yet. How can I check which version is on production?

**Comment by travi** [comment]
from what i understand, the fix is out to production, but at least didnt fully solve the issue. my team is seeing similar problems. 

the current fix was made at the application server level, but i'm curious if there is a size check earlier in the process that prevents the webhook from even reaching the application.

i still haven't been able to find any docs on the contents of the webhook payload, so i'm not sure what contributes to the size. without that information, i don't know what else to dig into from our side.

@Realtin @janl could this issue be re-opened until a full solution is handled?

**Comment by travi** [comment]
the fix that was rolled out this week resolved this problem for us. thanks for getting this one taken care of 😄

**Comment by DaRaFF** [comment]
Yes, it also works for our projects. Awesome, thank you!
