### ISSUE TITLE
Greenkeeper App updates closed PRs

### ISSUE THREAD

**Issue by gr2m** [greenkeeperio/greenkeeper#519]
- https://github.com/hoodiehq/couchdb-calculate-session-id/pull/21#issuecomment-331324132
- https://github.com/hoodiehq/hoodie-app-tracker/pull/150#issuecomment-331325579

**Comment by Realtin** [comment]
yep, I have seen this before. The github webhook `pull_request/closed` got lost somewhere on its way. So in our database the pull request is still open. I can update that manually for now.
It might make sense to check if a pull request is closed **on github** before commenting? because we do already check for it in our database :)

**Comment by travi** [comment]
i've been seeing a few of these again recently as well. after opening the new PR from the link in the comment and merging that PR, i was kind of expecting that to clean it up. however, i was still seeing additional comments added. i assume that means that the webhook you're listening for doesn't fire if it is already closed? maybe there another part of the flow of merging a PR from a comment that could help clean this up?

this is another reason why i'm interested in https://github.com/greenkeeperio/greenkeeper/issues/421, since the comment is actually always extra work with my workflow. now that i see [from the new docs](https://greenkeeper.io/docs.html#ignoring-dependencies) that the `greenkeeper` block in `package.json` can be used for config, maybe i can find some time to put a PR together.

**Comment by Realtin** [comment]
@travi If you have trouble with the setup of the dev Environment ping me on the intercom help chat. It isn't properly documented yet.

**Comment by travi** [comment]
thank you for the offer. i will let you know what i find. i can't promise that i'll get to it right away, but i'll be in touch if i have trouble.

i'm also in your slack if that is easier. i haven't really seen any activity in there, so maybe you aren't actually using that yet

**Comment by travi** [comment]
i've seen more of these pop up over the weekend:

* https://github.com/travi/hapi-react-router/pull/302

**Comment by travi** [comment]
heres another where i've been noticing this behavior: https://github.com/travi/redux-fetch-middleware/pull/134

**Comment by nsutclif** [comment]
I hit this issue too:
https://github.com/nsutclif/voipms-monitor/pull/153

**Comment by janl** [comment]
This should be a lot more reliable now. Please re-open if you see this again.
