### ISSUE TITLE
Automated test run couldn’t be detected within five minutes

### ISSUE THREAD

**Issue by jdalton** [greenkeeperio/greenkeeper#53]
My [repos](https://github.com/lodash/lodash-cli/pull/48) run sauce labs as I imagine many others do and as such they take longer than 5 minutes to complete. 

I know [gitter](https://gitter.im/lodash/lodash) is able to log/notify in its activity panel the pass/fail of runs (even those with saucelabs) without issue so I figure there's got to be a way of doing it properly without the 5 minute timeout.

<img width="305" alt="screen shot 2015-10-11 at 10 30 59 am" src="https://cloud.githubusercontent.com/assets/4303/10417985/312e01f4-7003-11e5-88d0-e04f3db79edf.png">

**Comment by boennemann** [comment]
Hey @jdalton,

sorry for the unclear wording. We don't have a five minute timeout for tests passing or failing, but for tests _starting_. There is no definite way of telling whether a repo has CI configured or not. This is why we have to set this timeout. E.g. Travis sets the status to pending once it picks up the commit, which usually takes a few seconds and not even nearly five minutes.

We couldn't find anything in the logs, but we see that you're receiving PRs as "untested" even though tests are running. This seems to be a bug on our side. We'll investigate this now.

Best,
Stephan

**Comment by skddc** [comment]
We have the same issue. Tests always run, but Travis can be really slow to start them. In my experience it always takes longer than just a few seconds with our repos.

**Comment by boennemann** [comment]
Hey @jdalton and @skddc,

this is fixed now. Instead of using a timeout to determine whether a CI is configured we're now using the status of the default_branch. If that doesn't have a state attached to it, we assume no CI is configured.

This means untested PRs are created instantly and tested branches will be deleted, or opened whenever the final status is there, even if it takes some time.

Best,
Stephan

**Comment by jdalton** [comment]
Woot!
