### ISSUE TITLE
Deleted repo still pending in the list

### ISSUE THREAD

**Issue by bahmutov** [greenkeeperio/greenkeeper#541]
We have enabled greenkeeper on our public example repos (thanks!) but one of the repos initially enabled was deleted (it was an experiment no longer needed). But it still shows up under account and we cannot delete it from greenkeeper!

The yellow repo in the image

<img width="652" alt="screen shot 2017-10-20 at 12 03 52 pm" src="https://user-images.githubusercontent.com/2212006/31830727-1aab2884-b58f-11e7-980b-5093612f096d.png">

Our account is `cypress-io` and we appreciate help with this little issue

**Comment by Realtin** [comment]
Unfortunately GitHub does not send a webhook when a repo was deleted, so Greenkeeper does not get notified and got the chance to delete the documents regarding the pull request and repository in the database. 
If Greenkeeper would try to communicate (create a new branch ect.) to the repo it would get an error from GitHub but since the initial pull request was not merged, Greenkeeper ignores this repo (and never knows about it's deletion)

I'll delete it from the database and contact GitHub about how useful a webhook like this could be.

Thanks for reporting!

**Comment by bahmutov** [comment]
Thank you for the resolution. Would it make sense to have a "sweeper" task that goes and checks repos existence every day for example? Then it could delete the project if repo is gone

**Comment by Realtin** [comment]
oh I found out it does send a webhook but Greenkeeper doesn't have actions for it!  I'll make a ticket about handling those events!

**Comment by Realtin** [comment]
https://github.com/greenkeeperio/greenkeeper/issues/543
