### ISSUE TITLE
Keep version range & syntax on dependency upgrade

### ISSUE THREAD

**Issue by dominique-mueller** [greenkeeperio/greenkeeper#550]
I'd love to see Greenkeeper being more aware of the dependency I've defined, in particular the version range as well as the version syntax.

For example: This PR (https://github.com/dominique-mueller/automatic-release/pull/46/files) upgrades TypeScript to a newer version. In particular, it increases the version number from `1.5.x` to `~1.6.1`. In my expectations, however, Greenkeeper should upgrade to `1.6.x` instead, thus
- keeping the full patch version range
- keeping the version syntax (the `x` is much easier to understand than the `~` sign in my opinion).

Any opinions on this idea?

**Comment by janl** [comment]
@dominique-mueller we agree that it would be nice if we could keep the syntax, but the options are very varied, which makes correct implementation quite a bit of a pain, in part because the underlying libraries we are using do not support the full range.

We’re happy to accept a PR about this, tho. Closing until further replies.

**Comment by dominique-mueller** [comment]
That's a pitty, yet understandable.

For everyone that's interested in this issue, [Renovate](https://github.com/renovatebot/renovate) actually keeps the `x.x.x` syntax.
