### ISSUE TITLE
Should lockfiles be committed for libraries with greenkeeper?

### ISSUE THREAD

**Issue by ismay** [greenkeeperio/greenkeeper#569]
This is not a bug report or a feature request, but rather a request for feedback on best practices when using greenkeeper for an npm library. On a PR for a library I maintain I was recently informed that it's not a good idea to commit lockfiles (https://github.com/ismay/stylelint-no-unsupported-browser-features/pull/51#issuecomment-355085677).

Now this makes sense, but the way I see it, when using greenkeeper (and greenkeeper-lockfile) committing lockfiles should be fine right? Am I correct in assuming that greenkeeper will run my CI tests for each minor and major update of a dependency and thus still inform me of failing tests? Or am I mistaken and should I remove the lockfile?

**Comment by pvdlg** [comment]
The problem you'll face by using lockfile is that currently Greenkeeper will not test your project for in range dependencies update due to #506.

If your project depends on `some-module` version `^1.0.0`, with the last version being `1.0.0`, when `some-package` release a new version `1.0.1`, all your users will end up with the version `1.0.1` (that's the beauty of npm and SemVer!). 

Greenkeeper will automatically make sure that all your tests are still passing with the version `1.0.1` of `some-module`. This way you are assured that your users won't experience issues.
If you are using a `package-lock.json` or a `yarn.lock`, Greenkeeper will skip those tests due to #506. So if `some-module` mistakingly break something in `1.0.1`, Greenkeeper won't tell you if you are using a lockfile, until #506 is resolve.

**Comment by ismay** [comment]
Ok, I understand. That’s too bad. So now I’ll have to remove the lockfiles, greenkeeper-lockfile and the token.. 🤦‍♂️ Just got it set up 😋

**Comment by pvdlg** [comment]
Or you can propose a PR that fix #506 ;)

**Comment by ismay** [comment]
I’d love to, but I think it’s a bit beyond my expertise. Don’t get me wrong, I appreciate that this is open source and I should’ve checked the issues before I got it set up 😊

**Comment by espy** [comment]
We’re moving forward with fixing #506, and we’re collecting some more info in that issue on whether our proposed solution is useful for everyone. Once that’s in you could again use lockfiles the way you describe in the opening post. Whether that’s a good idea or not depends on the repo, for a project it makes sense, for a library it can be counterproductive, but you already know that. The opening post in #506 has more details on which type of lockfile makes sense when (shrinkwrap vs yarn and package-lock).
