### ISSUE TITLE
Multiples issues

### ISSUE THREAD

**Issue by ajsb85** [greenkeeperio/greenkeeper#576]
Hi!

I have multiples issues in my private repository

![image](https://user-images.githubusercontent.com/663460/34824131-8187fe36-f6cd-11e7-9221-b952e620c1ec.png)

**Comment by ajsb85** [comment]
Again, SPAM from @greenkeeperio-bot 

![image](https://user-images.githubusercontent.com/663460/34962608-b0af3e16-fa44-11e7-9b20-ea690e2e835a.png)

**Comment by travi** [comment]
do you happen to have the "All repositories" radio checked in the greenkeeper github app settings? changing that value to "Only select repositories" avoids some issues like this because it waits until you manually add the repository to the list of those managed by greenkeeper (which you can then do after you've configured ci etc). it doesnt explain why you are getting so many duplicate issues opened, but it could help you avoid even the first one.

**Comment by Realtin** [comment]
@ajsb85 Sorry for not answering sooner 😞 
We had a queue backup at that time: https://twitter.com/greenkeeperio/status/951136248936181760 and our efforts to solve the underlying problem probably caused some duplicated jobs being run such as this timeout issue job.
