### ISSUE TITLE
SPAM in the branches

### ISSUE THREAD

**Issue by ajsb85** [greenkeeperio/greenkeeper#615]
Dearest.

We have noise in our repositories.

![image](https://user-images.githubusercontent.com/663460/36200201-31c30638-117c-11e8-8617-6b52bde03c0f.png)

**Comment by Realtin** [comment]
Hey @ajsb85 
what are the names of the repositories?

**Comment by ajsb85** [comment]
Hi, @Realtin 

I already deleted the branches.

https://github.com/flyve-mdm/glpi-plugin

**Comment by ajsb85** [comment]
Hi, @btry

Could you describe the behaviour?

Thanks

**Comment by Realtin** [comment]
Hey @ajsb85 

This happened because `conventional-changelog-cli` release multiple versions (all of them in your version range) in a short amount of time and at least one of that versions broke your ci build. 

Then greenkeeper creates an issue informing you of this problem and created some branches in order to give you the option to pin this dependency to a version that does not break things anymore. A bit later `conventional-changelog-cli` released the version that fixed their faulty version and the ci build was passing again. but since the greenkeeper issue was still open greenkeeper will only delete these branches when the issue is closed. That is why you had quite a few branches for that dependency.

So it really is a feature and not a bug ;)

**Comment by btry** [comment]
Hi @Realtin 

I disagree : ```conventional-changelog-cli``` is used only when we create an archive of our project, and for now this is done only manually. the CI does not handles this yet. 

If I read the log of a failed build, the failure is related to unit  tests for PHP only, and ```conventional-changelog-cli``` is not related to the failure.

For example, look this issue
https://github.com/flyve-mdm/glpi-plugin/issues/323

and the first job of the branch created by greenkeeper
https://travis-ci.org/flyve-mdm/glpi-plugin/jobs/340541346

The failure in this job is related to a fine tuning of a composer package for our unit tests. All jobs suffered the same issue for this build.

I think the context is the following : 
- we did domething which broke our unit tests
- in the mean  time an update was  released for ```conventional-changelog-cli``` and detected by greenkeeper
- greenkeeper tries to build the project with the updated package
- the build still fails because we did not fixed our unit tests yet
- greenkeeper sees the failure and reports that ```conventional-changelog-cli``` update breaks our project (but thisis false, because it was broken before this build)

**Comment by Realtin** [comment]
True!  Greenkeeper just *assumed* it was `conventional-changelog-cli`s fault!

**Comment by btry** [comment]
Do you think you could enhance the analysis ability of greenkeeper to no longer be wrong with such scenario ?

**Comment by Realtin** [comment]
Greenkeeper only reads the ci status on github so it only knows if it was a success or a failure and nothing more. For an enhanced analysis we would probably need access to CI logs which is out of scope for greenkeeper.

**Comment by btry** [comment]
I understand that reading build logs would be complex to handle, and/or out of scope of the greenkeeper.

However, maybe the following could be in the scope of Greenkeeper : 

If Greenkeeper creates a branch and a commit to try a newer version of a package, maybe it would be sufficient to read the build status of the parent commit. This way, the bot can detect that a failure on his build may not be related to an update of a package.

It might be even better to not try to build with updated packages if the base branch is already broken.
