### ISSUE TITLE
Once a PR gets merged automatically close all others that match the dependency/range

### ISSUE THREAD

**Issue by dbkaplun** [greenkeeperio/greenkeeper#62]
Edit: by @boennemann: Original title "New versions should update existing PRs rather than issuing new PRs"

Or at least close the old PR!

**Comment by michaelcontento** [comment]
:+1: as the current fast release cycle of babel is quite annoying :disappointed:

**Comment by AdriVanHoudt** [comment]
or close the old ones and delete the branch and then open new pr

**Comment by boennemann** [comment]
Hey y'all,

thanks for the feedback on this. We're definitely seeing this as a problem and we have a way in mind to address it. We're working on a feature where we'll add GitHub's "Closes #$PR` syntax to all new PR's of a single dependency, and update all old ones as well. That way humans may decide which version/range the want to go with and once the decision is made, all the "noise" will be closed accordingly.

Let me give you some background on why we chose this approach:

First of all Greenkeeper is designed to make visible how different dependencies change and how that affects your projects. In the babel case, that most of you are probably referring to, that worked. It became painfully clear what happens if you push out new versions after pulling an [all-nighter](https://babeljs.io/blog/2015/10/29/6.0.0/). All of this could've been avoided using npm's dist-tags to communicate stability. We don't want to lay all blame on babel, when you're having a bad experience with Greenkeeper. We're the [messenger](https://en.wikipedia.org/wiki/Shooting_the_messenger) in this case though. We'll work on documentation and blog-posts to better educate the community about best-practices.

We won't implement auto-closing or updating of existing PRs, because it is against our philosophy. Greenkeeper wants to automate chores, it doesn't want to take decisions or responsibility. Greenkeeper is designed to maximally reduce friction. Ideally all that's left for humans to do, is to take said decisions and responsibility, without the repetitive work involved. That's ultimately what we're good at.

Thanks again for your feedback.

Best,
Stephan

**Comment by AdriVanHoudt** [comment]
Nice explanation! I would still like the autoclose option but this way I just deal with the last PR and it will do the same so fine. Thanks for taking notice of this issue, was probably the biggest issue I have with greenkeepers (apart from the fact that it won't keep x's in place on update), thanks!

**Comment by mikeal** [comment]
Great stuff :)

**Comment by boennemann** [comment]
As I promised a blog-post on this topic, here it is: [One simple trick for JavaScript package maintainers to avoid breaking their user’s software and to ship stable releases](https://medium.com/greenkeeper-blog/one-simple-trick-for-javascript-package-maintainers-to-avoid-breaking-their-user-s-software-and-to-6edf06dc5617)

**Comment by boennemann** [comment]
Alright everyone,

we're happy to tell you that we've shipped this feature now. 

## How does it work?

We've decided to go the following route: Whenever you merge a Greenkeeper pull request we will delete the branch of that PR, as well as all branches (hence also closing the PRs) opened by Greenkeeper, for the same dependency, that have lower versions as the one being merged, or when they match the same version range.

Example:

Open PRs:
xyz @ ~10.0.0,  ~10.0.1, ~10.0.2, ~10.1.0, ~10.1.1, ~10.2.0, 11.0.0

Closing ~10.0.0 will delete ~10.0.0, ~10.0.1, ~10.0.2
Closing ~10.1.0 will delete ~10.0.0, ~10.0.1, ~10.0.2, 10.1.0, ~10.1.1
Closing ~10.2.0 will delete all except 11.0.0
Closing ~11.0.0 will delete all

## How can I get this?

We are rolling this out for all newly enabled repositories. If you want to opt into this behavior then disable your repository and enable it again.

Once we've gathered enough feedback we will enable this for all projects.


Thanks for your input and patience.

Best,
Stephan

**Comment by ahmadnassri** [comment]
amazing, great work!

**Comment by wenzowski** [comment]
This is working beautifully. Thanks! :smile:
