### ISSUE TITLE
keep level of `allowance`

### ISSUE THREAD

**Issue by AdriVanHoudt** [greenkeeperio/greenkeeper#64]
see https://github.com/AdriVanHoudt/Hapi-Boombox/pull/33/files
Comes down to that I allow 11.0.x but that the pr goes to 11.1.0, I would like to greenkeeper to go to 11.1.x

**Comment by finnp** [comment]
Other cases that relate to this
- single majors, e.g. `2` https://github.com/greenkeeperio/greenkeeper/issues/242 https://github.com/greenkeeperio/greenkeeper/issues/103
- explicit ranges, e.g. `2.0.0 < 3` https://github.com/greenkeeperio/greenkeeper/issues/254

**Comment by AdriVanHoudt** [comment]
is there any progress on this? Or is something holding this up?

**Comment by boennemann** [comment]
Hey @AdriVanHoudt,

I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations.

With the new Greenkeeper this issue is resolved and you can try it out today: https://github.com/integration/greenkeeper
Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan

**Comment by AdriVanHoudt** [comment]
@boennemann I enabled it for test repo to check it out. Also I kinda like the way Snyk allows you to enable it for repos. They have an easy overview on their website and how I enabled it now on github is more cumbersome. I do understand that this is a `real` integration while Snyk is just using the api I think.

**Comment by AdriVanHoudt** [comment]
@boennemann it still changes the notation in the PR's see https://github.com/Salesflare/hapi-plugin-mysql/pull/53/files
I really want to be able to just click merge and go sit under an actual palm tree 🌴  but this is really prevents me from doing that :/

**Comment by AdriVanHoudt** [comment]
@boennemann another example https://github.com/Salesflare/hapi-csv/pull/11/files
