### ISSUE TITLE
Greenkeeper creates PR to non-existing versions

### ISSUE THREAD

**Issue by grantila** [greenkeeperio/greenkeeper#716]
I got this PR a month ago about upgrading to sinon 5.0: https://github.com/grantila/already/pull/2

The only problem is, the latest version of sinon is 4.5: [npmjs](https://www.npmjs.com/package/sinon) [package.json](https://github.com/sinonjs/sinon/blob/master/package.json#L4). Where are you getting 5.0 from?

**Comment by espy** [comment]
Hi @grantila ,

Sinon accidentally released a `5.0.0.` after `4.1.4` when they meant to release `"5.0.0-next.1`, which appeared shortly after. They then removed `5.0.0` again. You can see the remains of the release in some unused commits [here](https://github.com/sinonjs/sinon/commit/2e455c63ba1305faca9e173c44f82de7a42fed4e), the changelog reads `5.0.0-next`, but the release version is `5.0.0`, and [here in the package.json](https://github.com/sinonjs/sinon/commit/d93cb9dd05d59921725060ab5bb5f221c6bff30e).

Since there are no unpublish events coming from npm, handling this properly is a bit tricky, I’m afraid. 

Hope that answers your question!

**Comment by grantila** [comment]
Thanks for the explanation!
