### ISSUE TITLE
Mention the “updating from” version in the pull request

### ISSUE THREAD

**Issue by janl** [greenkeeperio/greenkeeper#77]
> @greenkeeperio feature request: can you mention the previous version in the PR? eg, "updating handlebars from 3.0.2 to 4.0.5" :)

— https://twitter.com/rstacruz/status/668273828838027264

**Comment by tunnckoCore** [comment]
:+1:

**Comment by iamstarkov** [comment]
wanted this feature too

**Comment by boennemann** [comment]
I'm happy to tell you that we've just rolled out the new Greenkeeper that is based on GitHub integrations.

With the new Greenkeeper this issue is resolved and you can try it out today: https://github.com/integration/greenkeeper
Installing the integration will automatically enable Greenkeeper for all repos that you can grant access for, and that have a package.json file present.

Please be aware that this is currently in its early phase. Before installing it we recommend disabling the old Greenkeeper.

Thanks for your feedback.
We'd love to hear what you think about the new Greenkeeer as well.

Best,
Stephan
