### ISSUE TITLE
In range update

### ISSUE THREAD

**Issue by holgergp** [greenkeeperio/greenkeeper#909]
Hi Greenkeeper Team,

today I got an out-of-range update for _enzyme-adapter-react-16_ to version 1.5.0

> The version 1.5.0 is not covered by your current version range.

In my package.json I stated a version of ^1.4.0. 
I assumed that a version update to 1.5.0 should have been an in-range-update, as it should be covered by ^1.4.0 and thus the PR should have been merged automatically.
This is surely no critical thing, but I like to understand the upgrade strategy a little better.

Thanks for your awesome work!

**Comment by espy** [comment]
Hi Holger, thanks for getting in touch. We’ve found a few errors in the way Greenkeeper communicates when handling updates from monorepo releases like Enzyme. It does the right _things_ (commits etc.), but the PR and issue texts aren’t always correct. It’s a bit folded in to [this issue](https://github.com/greenkeeperio/greenkeeper/issues/894) which we’re working on right now (which is why I’ll close this issue). Once we’re done, PR and issue texts will be correct for monorepo releases and more informative in general. So this shouldn’t happen again.

Thanks for the thanks, by the way! Much appreciated ✊
