### ISSUE TITLE
update npm-shrinkwrap.json if exists

### ISSUE THREAD

**Issue by cben** [greenkeeperio/greenkeeper#96]
If a project contains `npm-shrinkwrap.json`, simply updating `package.json` has no effect;
to avoid confusion, any commit touching `package.json` should also re-run `npm shrinkwrap`.

At a minimum, until greenkeeper supports that, it'd be helpful if the PR text at least had a reminder that a shrinkwrap might have to be re-generated.

(In theory, having a shrinkwrap makes it potentially meaningful to send a shrinkwrap-only PR whenever any (sub)dependency has a new version, even if it fits within the ranges specified by `package.json`.  But that's probably too noisy for most people.)

**Comment by mhaamann** [comment]
+1

**Comment by SpainTrain** [comment]
Something like this would be useful.

Thoughts on being more general?  For example, perhaps in `package.json` one can specify a run script for greenkeeper (e.g., `postgreenkeeper`) that is run before it creates the new commit?  This (or similar) could support the shrinkwrap use case while being general enough to support others.

**Comment by jedrichards** [comment]
I'm surprised this is the only issue mentioning shrinkwrapping and greenkeeper. Can't find much discussion about it via Google either. Am I missing something?

IMO pinning top level deps and using shrinkwrap is best practice for end products/production facing apps, so these sorts of private projects represent an untapped income stream for Greenkeeper since lack of shrinkwrap support is surely putting people off? I know it's putting me off adding Greenkeeper to private/professional projects.

**Comment by boennemann** [comment]
Hey y'all,

thanks for the feedback on shrinkwrap.
We are currently trying to figure out how we want to address this, as thing aren't that simple™.

How would you want the shrinkwrap file to be updated?

Regenerate the entire shrinkwrap on every update? Wouldn't that defeat the purpose of updating things in isolation, because other dependencies will be affected? And if we regenerate it, how do we know which npm version, or other client, we should be using to generate the shrinkwrap?

Do you only want top-level dependencies to be updated, or every single one in the entire tree? And how would you want to keep up with the extreme amount of pull requests we'd be sending then? If we update a dependency, should we take care of all underlying dependencies as well?

Aside from significantly more computing power needed to do these things, we need to find _satisfying_ answers to above questions, and we need to find out whether we can find a solution that wouldn't end in countless configuration parameters.
We are working on this, but unfortunately it takes some time to get it right.

In the meantime: We are interested in finding out why you are storing your shrinkwrap file inside the repository? Wouldn't it suffice to generate a shrinkwrap file on publish/deploy-time after tests have passed? We hope to get some more insight here.


Thanks and all the best,
Stephan

**Comment by cben** [comment]
2016-01-27 18:09 GMT+02:00 Stephan Bönnemann <notifications@github.com>:

> In the meantime: We are interested in finding out why you are storing your
> shrinkwrap file inside the repository? Wouldn't it suffice to generate a
> shrinkwrap file on publish/deploy-time after tests have passed? We hope to
> get some more insight here.
>
First, I'm developing an app, not a library.  If I were publishing an npm
package, I wouldn't have a shrinkwrap in the repo.

1. I want to my repository and my production to match.
    I want a commit to always run the same code, whether locally, on
Travis, or on Heroku/OpenShift.
    Conversely I want any update of dependencies in production to be
represented by a source commit.  (which is precisely greenkeeper's point)

2. My workflow has no separate step to build things before publish/deploy,
nor a place to store build artifacts.  I git push the source as-is to
Heroku/OpenShift.
    Not having build artifacts is a luxury not everyone can afford (and a
reproducibility risk not everyone is willing to take).  But it makes life
much simpler.

(Same reasons git submodule versions are part of the repo.  Unlike most
people I rather like submodules, and using them for a few non-npm deps.)

To be honest with myself, `npm-shrinkwrap.json` *is* a kind of build
artifact, so why am storing it in git?
Is it only because it's small enough and I'm sloppy?
No, shrinkwrap is special: it's not reproducible from source but also
depends on the current state of all npm packages, so there is no choice but
store it in the repo.

**Comment by jedrichards** [comment]
> We are currently trying to figure out how we want to address this, as thing aren't that simple™.

Hah, yep ... amen to that!

> Regenerate the entire shrinkwrap on every update? Wouldn't that defeat the purpose of updating things in isolation, because other dependencies will be affected?

In npm3's world with flat dependencies even updating a single top level dependency is going to potentially change that top level state? And what does updating something "in isolation" mean in that context? Yes it's just one change to package.json, but the resulting change to the dependency tree is not deterministic, that counts double since the public registry changes over time too!

For an app with a shrinkwrap file I'd like Greenkeeper to be able to say (this is a naive pseudo process, so bear with me if it has some logical holes):

1) Here's a single updated top-level dependency in your package.json
2) And here's a brand new arbitrarily different shrinkwrap file that snapshots node_modules having done `rm -rf node_modules; npm i; npm shrinkwrap` after adding the new top level dep
3) Here are the results of your tests
4) This process should be run-run after every commit on the branch

> And if we regenerate it, how do we know which npm version, or other client, we should be using to generate the shrinkwrap?

This could be taken from the `engines` field in package.json. Npm version should be the version deployed in lockstep with the Node version. Perhaps if `engines` is not present you don't process the shrinkwrap at all.

> Do you only want top-level dependencies to be updated, or every single one in the entire tree?

Only update top level deps. Updating a top level dep could cause a lot of changes in the shrinkwrap from the whole tree, that's ok?

> We are interested in finding out why you are storing your shrinkwrap file inside the repository. Wouldn't it suffice to generate a shrinkwrap file on publish/deploy-time after tests have passed?

When you deploy somewhere that does your CI, testing and building for production remotely using Node tools you want to lock down the dependency tree for those tools. It's no good having a non-deterministic tree of build tool deps manifest on your build server. Lock it down on every devs workstation, and lock it down on the build server too. Like @cben says above, any change to that tree should be in shape of a commit that updates package.json and shrinkwrap that passes through CI itself, like any other feature.

**Comment by assaf** [comment]
> In the meantime: We are interested in finding out why you are storing your shrinkwrap file inside the repository. Wouldn't it suffice to generate a shrinkwrap file on publish/deploy-time after tests have passed? We hope to get some more insight here.

First, it's so we know exactly what we're deploying – and therefore asking CI to test.  You've got one developer still on 1.1.0, but another already upgraded to 1.5.0: which of these will CI use? Does it always update to the latest, what if you don't want to use the latest (yet) in production? Or does it never update to the latest, what if you want it to? If something breaks in production, which version do you troubleshoot again? What if 1.5.0 is broken, how do you downgrade everyone – including the developer who just npm updated to 1.5.0 – back to 1.4.1?

**Comment by assaf** [comment]
> Regenerate the entire shrinkwrap on every update?

Yes. We have a Git pre-push hook that does it, so in Github our package matches our shrinkwraps, not a big problem.

> And if we regenerate it, how do we know which npm version, or other client, we should be using to generate the shrinkwrap?

https://docs.npmjs.com/files/package.json#engines

> Do you only want top-level dependencies to be updated, or every single one in the entire tree?

Top-level dependencies is what we're currently doing manually, and hoping greenkeeper could automate that manual process.

**Comment by assaf** [comment]
So this just happened:
- greenkeeper finds a new version of a dependency that unfortunately contains a bug
- creates branch, updates package.json, pushes to Github
- CI picks the branch, runs npm install
- npm install defaults to using shrinkwrap, which lists previous (non-buggy) version of dependency
- All tests are green

**Comment by jedrichards** [comment]
Considering the recent npm/left-pad snafu, it feels to me like shrinkwrapping and pinning versions on production projects has become an even more relevant discussion. Feels like there's an opportunity for Greenkeeper to step in here? And if Greenkeeper could support shrinkwrap and even combine results from say [Node Security Project](https://nodesecurity.io/) or [Snyk](https://github.com/Snyk/snyk) ... ? This would certainly be something I'd consider recommend my clients pay for on production projects.

**Comment by boennemann** [comment]
To let y'all know: We're building support for this, where we're using the PRs just like they're now, but we'll offer a script that handles shrinkwrap regeneration/updating on the user's CI. "Very soon" is all I can give you right now though.

Thanks for your patience,
Stephan

**Comment by hpurmann** [comment]
Hey @boennemann! Do you have any news on this?

**Comment by hpurmann** [comment]
I put together some ideas on how this could be achieved. Maybe it's helpful for someone willing to implement this.

## Shrinkwrap regeneration on dependency update on CI

1. If `package.json` has been updated, check if `npm-shrinkwrap.json` has updated as well. If both didn't or both did, skip all of this and just test. Otherwise, continue with the following steps.
1. Get the changed packages and their new versions from the diff of the branch commit with the base branch. We do have to support multiple package updates in the same branch (e.g. for the initial PR greenkeeper is doing).

    ```
    newPackages = [
      {
        name: 'moduleA',
        version: '1.2.1'
      },
      {
        name: 'moduleB',
        version: '2.1.5'
      }
    ]
    ```
1. Execute `npm install` with the old `npm-shrinkwrap.json` and updated `package.json` (no effect) file. The old dependencies will get installed.
1. Loop through `newPackages` and execute `npm install module@version` for each of them.
1. Execute `npm shrinkwrap --dev`
1. Add and commit the shrinkwrap changes and push them
1. Exit build early (with a failure to not trigger deploy)
1. CI will get notified because of the new commit and will run again. The check in step 1 will succeed (terminating the possible cycle) and a test with the fixed shrinkwrap will begin.

As a side note: While trying this on Travis, I accidentally build a non-terminating loop. Be careful 😜

**Comment by boennemann** [comment]
Hey all,

sorry for the long wait. The GitHub integration kept us busy, so that we could only tackle this now.

I just published [`greenkeeper-shrinkwrap`](https://www.npmjs.com/package/greenkeeper-shrinkwrap) which adds experimental shrinkwrap support to Greenkeeper projects. It only supports Travis CI for now, sorry ([We're working on more](https://github.com/greenkeeperio/greenkeeper-shrinkwrap/issues/5)).

Let us know what you think.

Best,
Stephan

**Comment by boennemann** [comment]
A quick update on this. We renamed `greenkeeper-shrinkwrap` to [`greenkeeper-lockfile`](https://github.com/greenkeeperio/greenkeeper-lockfile).

We added
* npm5 support
* yarn support
* [made it simple to add more CI services](https://github.com/greenkeeperio/greenkeeper-lockfile#contributing-a-ci-service)

Please let us know how it works for y'all.

I'm going to close this issue, but we're still trying to figure out how to best add server-side lockfile support.

Best,
Stephan

**Comment by boennemann** [comment]
We just deployed a change so that projects with lockfiles won't receive branches for in-range updates anymore: https://github.com/greenkeeperio/greenkeeper/releases/tag/v2.3.0
