### ISSUE TITLE
How to deal with issues with the initial PR

### ISSUE THREAD

**Issue by alexsheppard11** [greenkeeperio/greenkeeper#967]
Hi,
Greenkeeper has succesfully raised the initial PR, however I have a couple of questions as the docs seems to skim over the initial PR and what to do if there are dependency issues in it.

My _package.json_ has `"webpack": "^3.11.0"`, however Greenkeeper is updating this to `"webpack": "^4.20.2"`, which is causing compilation problems. Why is it updating webpack to version 4, given the `^`?

Secondly, am I free to commit to this branch to try and resolve these issues?

Thanks!

**Comment by hulkoba** [comment]
Hi Alex,
Greenkeeper is updating webpack to version 4, given the ^, because it is an out-of-range update.

You have to checkout the initial Greenkeeper-branch and downgrade your webpack dependency manually. To make sure Greenkeeper doesn’t nag you again on the next update, add a greenkeeper.ignore field to your package.json, containing the webpack dependency you don’t want to update.

```
// package.json
{
  …
  "greenkeeper": {
    "ignore": ["webpack"]
  }
}
```
